// frontend/counsela/src/components/Layout/Header.vue
<template>
  <header class="fixed top-0 inset-x-0 z-50 bg-white/80 backdrop-blur-xl border-b border-zinc-200/80 transition-all">
    <!-- {Main Nav} -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between gap-4">
      <!-- {Brand} -->
      <RouterLink to="/" class="flex items-center gap-2.5 group shrink-0">
        <div class="w-8 h-8 rounded-xl bg-black text-white flex items-center justify-center font-bold text-sm shadow-sm group-hover:scale-105 transition-transform">
          <svg class="w-4 h-4 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
            <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
            <polyline points="2 17 12 22 22 17"></polyline>
            <polyline points="2 12 12 17 22 12"></polyline>
          </svg>
        </div>
        <div class="flex items-baseline gap-1.5">
          <span class="font-bold text-lg tracking-tight text-zinc-950 group-hover:text-zinc-700 transition-colors">
            counsela
          </span>
        </div>
      </RouterLink>

      <!-- {Search} -->
      <button
        @click="triggerCommandPalette"
        class="hidden md:flex items-center gap-2.5 px-3.5 py-1.5 rounded-full border border-zinc-200/90 bg-zinc-50/80 hover:bg-white hover:border-zinc-400 text-zinc-400 hover:text-zinc-900 transition-all text-xs max-w-xs w-full shadow-2xs group"
        title="Buka Command Search (Ctrl+K atau ⌘K)"
      >
        <svg class="w-3.5 h-3.5 text-zinc-400 group-hover:text-zinc-900 transition-colors" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="11" cy="11" r="8"></circle>
          <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
        </svg>
        <span class="text-zinc-500 text-xs truncate">Cari advokat, dokumen, regulasi...</span>
        <kbd class="ml-auto px-1.5 py-0.5 text-[9px] font-mono font-medium text-zinc-400 bg-white border border-zinc-200 rounded-md">
          ⌘K
        </kbd>
      </button>

      <!-- {Nav Links} -->
      <nav class="hidden lg:flex items-center gap-1 text-xs">
        <RouterLink
          to="/"
          class="px-3.5 py-1.5 rounded-full transition-all font-medium"
          :class="isActive('/') ? 'bg-zinc-100 text-zinc-950 font-semibold' : 'text-zinc-600 hover:text-zinc-950 hover:bg-zinc-50'"
        >
          Beranda
        </RouterLink>

        <RouterLink
          to="/lawyers"
          class="px-3.5 py-1.5 rounded-full transition-all font-medium"
          :class="isActive('/lawyers') ? 'bg-zinc-100 text-zinc-950 font-semibold' : 'text-zinc-600 hover:text-zinc-950 hover:bg-zinc-50'"
        >
          Daftar Advokat
        </RouterLink>

        <RouterLink
          to="/about"
          class="px-3.5 py-1.5 rounded-full transition-all font-medium"
          :class="isActive('/about') ? 'bg-zinc-100 text-zinc-950 font-semibold' : 'text-zinc-600 hover:text-zinc-950 hover:bg-zinc-50'"
        >
          Tentang Kami
        </RouterLink>

        <RouterLink
          v-if="isAuthenticated && (isClient || isLawyer)"
          to="/consultations"
          class="px-3.5 py-1.5 rounded-full transition-all font-medium"
          :class="isActive('/consultations') ? 'bg-zinc-100 text-zinc-950 font-semibold' : 'text-zinc-600 hover:text-zinc-950 hover:bg-zinc-50'"
        >
          {{ isClient ? 'Konsultasi Saya' : 'Permintaan Masuk' }}
        </RouterLink>

        <RouterLink
          v-if="isAdmin"
          to="/users"
          class="px-3.5 py-1.5 rounded-full transition-all font-medium"
          :class="isActive('/users') ? 'bg-zinc-100 text-zinc-950 font-semibold' : 'text-zinc-600 hover:text-zinc-950 hover:bg-zinc-50'"
        >
          Kelola User
        </RouterLink>

        <RouterLink
          v-if="isAuthenticated && dashboardTarget"
          :to="dashboardTarget"
          class="px-3.5 py-1.5 rounded-full transition-all font-medium"
          :class="isActive(dashboardTarget) ? 'bg-zinc-100 text-zinc-950 font-semibold' : 'text-zinc-600 hover:text-zinc-950 hover:bg-zinc-50'"
        >
          Dashboard
        </RouterLink>
      </nav>

      <!-- {Auth} -->
      <div class="flex items-center gap-2">
        <template v-if="!isAuthenticated">
          <RouterLink
            to="/login"
            class="px-3.5 py-1.5 text-xs font-semibold text-zinc-600 hover:text-zinc-950 transition-colors"
          >
            Masuk
          </RouterLink>
          <RouterLink
            to="/register"
            class="px-4 py-2 text-xs font-semibold bg-black hover:bg-zinc-800 text-white rounded-full transition-all shadow-sm"
          >
            Daftar
          </RouterLink>
        </template>

        <template v-else>
          <div class="relative" ref="dropdownRef">
            <button
              @click="toggleUserMenu"
              class="flex items-center gap-2 px-3 py-1.5 rounded-full border border-zinc-200 bg-white hover:bg-zinc-50 transition-all text-xs"
              aria-label="Menu Pengguna"
            >
              <div class="w-6 h-6 rounded-full bg-zinc-900 text-white flex items-center justify-center text-[11px] font-mono font-bold uppercase">
                {{ userInitials }}
              </div>
              <span class="font-medium text-zinc-800 hidden sm:inline-block max-w-[100px] truncate">
                {{ userNameFirst }}
              </span>
              <svg class="w-3.5 h-3.5 text-zinc-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </button>

            <!-- {Dropdown} -->
            <div
              v-if="openUser"
              class="absolute right-0 mt-2 w-52 bg-white border border-zinc-200 rounded-2xl shadow-xl py-2 text-xs z-50 animate-in fade-in zoom-in-95 duration-100"
            >
              <div class="px-4 py-2.5 border-b border-zinc-100">
                <p class="font-bold text-zinc-900 truncate">{{ user?.nama }}</p>
                <p class="text-[11px] text-zinc-400 truncate mt-0.5">{{ user?.email }}</p>
                <span class="inline-block mt-1 text-[9px] font-mono font-semibold uppercase px-2 py-0.5 rounded-full bg-zinc-100 text-zinc-700">
                  {{ user?.role }}
                </span>
              </div>

              <RouterLink
                v-if="dashboardTarget"
                :to="dashboardTarget"
                @click="openUser = false"
                class="block px-4 py-2 text-zinc-700 hover:bg-zinc-50 font-medium transition-colors"
              >
                Dashboard
              </RouterLink>

              <RouterLink
                to="/consultations"
                @click="openUser = false"
                class="block px-4 py-2 text-zinc-700 hover:bg-zinc-50 font-medium transition-colors"
              >
                Daftar Konsultasi
              </RouterLink>

              <button
                @click="triggerCommandPalette"
                class="w-full text-left px-4 py-2 text-zinc-700 hover:bg-zinc-50 font-medium transition-colors flex items-center justify-between"
              >
                <span>Cari Cepat</span>
                <kbd class="text-[9px] font-mono bg-zinc-100 px-1.5 py-0.5 rounded">⌘K</kbd>
              </button>

              <div class="my-1 border-t border-zinc-100"></div>

              <button
                @click="handleLogout"
                class="w-full text-left px-4 py-2 text-red-600 hover:bg-red-50 font-semibold transition-colors flex items-center justify-between"
              >
                <span>Keluar</span>
              </button>
            </div>
          </div>
        </template>
      </div>
    </div>
  </header>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuth } from '../../composables/useAuth'

const route = useRoute()
const router = useRouter()
const { user, logout, isAuthenticated, isAdmin, isLawyer, isClient } = useAuth()

const openUser = ref(false)
const dropdownRef = ref(null)

const toggleUserMenu = () => {
  openUser.value = !openUser.value
}

const triggerCommandPalette = () => {
  openUser.value = false
  window.dispatchEvent(new CustomEvent('open-counsela-palette'))
}

const handleLogout = async () => {
  openUser.value = false
  await logout()
  router.push('/login')
}

const isActive = (path) => route.path === path

const userInitials = computed(() => {
  return user.value?.nama ? user.value.nama.charAt(0).toUpperCase() : 'U'
})

const userNameFirst = computed(() => {
  return user.value?.nama ? user.value.nama.split(' ')[0] : 'Akun'
})

const dashboardTarget = computed(() => {
  if (isClient.value) return '/client-dashboard'
  if (isLawyer.value) return '/lawyer-dashboard'
  if (isAdmin.value) return '/admin-dashboard'
  return null
})

const handleClickOutside = (e) => {
  if (dropdownRef.value && !dropdownRef.value.contains(e.target)) {
    openUser.value = false
  }
}

onMounted(() => {
  window.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  window.removeEventListener('click', handleClickOutside)
})
</script>

// frontend/counsela/src/components/Layout/Header.jsx
import { useState, useEffect } from "react"
import { Link, useNavigate, useLocation } from "react-router-dom"
import useAuth from "../../hooks/useAuth"
import { useTheme } from "../../context/ThemeContext"

const Icons = {
  Menu: () => (
    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
    </svg>
  ),
  Close: () => (
    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
    </svg>
  ),
  Home: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
    </svg>
  ),
  Lawyer: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
    </svg>
  ),
  About: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Consultation: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
    </svg>
  ),
  Dashboard: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
    </svg>
  ),
  Users: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
    </svg>
  ),
  Login: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
    </svg>
  ),
  Register: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
    </svg>
  ),
  Logout: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
    </svg>
  ),
  Sun: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
    </svg>
  ),
  Moon: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
    </svg>
  ),
  ChevronDown: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
    </svg>
  ),
}

const Header = () => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const [showUserMenu, setShowUserMenu] = useState(false)
  const { user, logout, isAuthenticated, isAdmin, isLawyer, isClient } = useAuth()
  const { darkMode, toggleDarkMode } = useTheme()
  const navigate = useNavigate()
  const location = useLocation()

  // Tutup menu saat pindah halaman
  useEffect(() => {
    setShowUserMenu(false)
    setIsMobileMenuOpen(false)
  }, [location.pathname])

  const handleLogout = async () => {
    await logout()
    setShowUserMenu(false)
    setIsMobileMenuOpen(false)
    navigate("/login")
  }

  // Base nav links untuk semua user
  const navLinks = [
    { path: "/", label: "Beranda", icon: Icons.Home },
    { path: "/about", label: "Tentang", icon: Icons.About },
    { path: "/lawyers", label: "Lawyers", icon: Icons.Lawyer },
  ]

  // Dashboard link berdasarkan role
  const dashboardLink = () => {
    if (isClient) return "/client-dashboard"
    if (isLawyer) return "/lawyer-dashboard"
    if (isAdmin) return "/admin-dashboard"
    return null
  }

  const getDashboardLabel = () => {
    if (isClient) return "Dashboard"
    if (isLawyer) return "Dashboard"
    if (isAdmin) return "Admin Panel"
    return null
  }

  // Menu khusus admin
  const adminLinks = [
    { path: "/users", label: "Kelola User", icon: Icons.Users },
  ]

  const isActive = (path) => location.pathname === path

  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/95 dark:bg-gray-900/95 backdrop-blur-md shadow-lg py-3">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            {/* Logo */}
            <Link to="/" className="flex items-center gap-2 group">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 flex items-center justify-center shadow-md transition-transform group-hover:scale-105">
                <span className="text-white font-bold text-xl">⚖️</span>
              </div>
              <span className="text-xl font-bold text-gray-800 dark:text-white">
                Counsela
              </span>
            </Link>

            {/* Desktop Navigation */}
            <nav className="hidden md:flex items-center gap-1">
              {navLinks.map((link) => (
                <Link
                  key={link.path}
                  to={link.path}
                  className={`px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 flex items-center gap-2 ${
                    isActive(link.path)
                      ? "bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
                      : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                  }`}
                >
                  <link.icon />
                  {link.label}
                </Link>
              ))}

              {/* Link Konsultasi untuk Client & Lawyer */}
              {isAuthenticated && (isClient || isLawyer) && (
                <Link
                  to="/consultations"
                  className={`px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 flex items-center gap-2 ${
                    isActive("/consultations")
                      ? "bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
                      : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                  }`}
                >
                  <Icons.Consultation />
                  {isClient ? "Konsultasi Saya" : "Orderan Masuk"}
                </Link>
              )}

              {/* Menu Admin - Tambahan untuk admin */}
              {isAdmin && (
                <>
                  {adminLinks.map((link) => (
                    <Link
                      key={link.path}
                      to={link.path}
                      className={`px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 flex items-center gap-2 ${
                        isActive(link.path)
                          ? "bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
                          : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                      }`}
                    >
                      <link.icon />
                      {link.label}
                    </Link>
                  ))}
                </>
              )}

              {/* Dashboard untuk masing-masing role */}
              {isAuthenticated && dashboardLink() && (
                <Link
                  to={dashboardLink()}
                  className={`px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 flex items-center gap-2 ${
                    isActive(dashboardLink())
                      ? "bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
                      : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                  }`}
                >
                  <Icons.Dashboard />
                  {getDashboardLabel()}
                </Link>
              )}
            </nav>

            {/* Right Side - Auth & Theme */}
            <div className="hidden md:flex items-center gap-3">
              <button
                onClick={toggleDarkMode}
                className="p-2 rounded-xl text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-800 transition-all duration-200"
              >
                {darkMode ? <Icons.Sun /> : <Icons.Moon />}
              </button>

              {!isAuthenticated ? (
                <>
                  <Link
                    to="/login"
                    className="px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 flex items-center gap-2 text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                  >
                    <Icons.Login />
                    Masuk
                  </Link>
                  <Link
                    to="/register"
                    className="px-5 py-2 rounded-xl text-sm font-semibold transition-all duration-200 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white shadow-md hover:shadow-lg"
                  >
                    Daftar
                  </Link>
                </>
              ) : (
                <div className="relative">
                  <button
                    onClick={() => setShowUserMenu(!showUserMenu)}
                    className="flex items-center gap-2 px-3 py-2 rounded-xl text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800 transition-all duration-200"
                  >
                    <div className="w-8 h-8 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 flex items-center justify-center shadow-md">
                      <span className="text-white text-sm font-semibold">
                        {user?.nama?.charAt(0).toUpperCase() || "U"}
                      </span>
                    </div>
                    <span className="text-sm font-medium hidden lg:block">
                      {user?.nama?.split(" ")[0]}
                    </span>
                    <Icons.ChevronDown />
                  </button>

                  {showUserMenu && (
                    <div className="absolute right-0 mt-2 w-56 bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden z-50">
                      <div className="p-3 border-b border-gray-200 dark:border-gray-700">
                        <p className="text-sm font-semibold text-gray-800 dark:text-white">{user?.nama}</p>
                        <p className="text-xs text-gray-500 truncate">{user?.email}</p>
                        <p className="text-xs text-blue-600 dark:text-blue-400 mt-1 capitalize">{user?.role}</p>
                      </div>
                      <button
                        onClick={handleLogout}
                        className="w-full px-4 py-3 text-left text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 transition flex items-center gap-2"
                      >
                        <Icons.Logout />
                        Keluar
                      </button>
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Mobile Menu Button */}
            <button
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              className="md:hidden p-2 rounded-xl text-gray-700 dark:text-white"
            >
              {isMobileMenuOpen ? <Icons.Close /> : <Icons.Menu />}
            </button>
          </div>
        </div>
      </header>

      {/* Mobile Menu Overlay */}
      {isMobileMenuOpen && (
        <div className="fixed inset-0 z-40 md:hidden">
          <div className="fixed inset-0 bg-black/50" onClick={() => setIsMobileMenuOpen(false)} />
          <div className="fixed top-0 right-0 h-full w-72 bg-white dark:bg-gray-900 shadow-xl p-5 pt-20 overflow-y-auto">
            <nav className="flex flex-col gap-2">
              {navLinks.map((link) => (
                <Link
                  key={link.path}
                  to={link.path}
                  onClick={() => setIsMobileMenuOpen(false)}
                  className={`flex items-center gap-3 px-4 py-3 rounded-xl transition ${
                    isActive(link.path)
                      ? "bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
                      : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                  }`}
                >
                  <link.icon />
                  {link.label}
                </Link>
              ))}

              {isAuthenticated && (isClient || isLawyer) && (
                <Link
                  to="/consultations"
                  onClick={() => setIsMobileMenuOpen(false)}
                  className={`flex items-center gap-3 px-4 py-3 rounded-xl transition ${
                    isActive("/consultations")
                      ? "bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
                      : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                  }`}
                >
                  <Icons.Consultation />
                  {isClient ? "Konsultasi Saya" : "Orderan Masuk"}
                </Link>
              )}

              {/* Admin menu di mobile */}
              {isAdmin && (
                <>
                  {adminLinks.map((link) => (
                    <Link
                      key={link.path}
                      to={link.path}
                      onClick={() => setIsMobileMenuOpen(false)}
                      className={`flex items-center gap-3 px-4 py-3 rounded-xl transition ${
                        isActive(link.path)
                          ? "bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
                          : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                      }`}
                    >
                      <link.icon />
                      {link.label}
                    </Link>
                  ))}
                </>
              )}

              {isAuthenticated && dashboardLink() && (
                <Link
                  to={dashboardLink()}
                  onClick={() => setIsMobileMenuOpen(false)}
                  className={`flex items-center gap-3 px-4 py-3 rounded-xl transition ${
                    isActive(dashboardLink())
                      ? "bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
                      : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                  }`}
                >
                  <Icons.Dashboard />
                  {getDashboardLabel()}
                </Link>
              )}

              <div className="h-px bg-gray-200 dark:bg-gray-700 my-2" />

              <button
                onClick={toggleDarkMode}
                className="flex items-center gap-3 px-4 py-3 rounded-xl text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800 transition"
              >
                {darkMode ? <Icons.Sun /> : <Icons.Moon />}
                {darkMode ? "Mode Terang" : "Mode Gelap"}
              </button>

              {!isAuthenticated ? (
                <>
                  <Link
                    to="/login"
                    onClick={() => setIsMobileMenuOpen(false)}
                    className="flex items-center gap-3 px-4 py-3 rounded-xl text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800 transition"
                  >
                    <Icons.Login />
                    Masuk
                  </Link>
                  <Link
                    to="/register"
                    onClick={() => setIsMobileMenuOpen(false)}
                    className="flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-semibold mt-2"
                  >
                    <Icons.Register />
                    Daftar Sekarang
                  </Link>
                </>
              ) : (
                <>
                  <div className="flex items-center gap-3 px-4 py-3">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 flex items-center justify-center">
                      <span className="text-white font-semibold">{user?.nama?.charAt(0).toUpperCase()}</span>
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-gray-800 dark:text-white">{user?.nama}</p>
                      <p className="text-xs text-gray-500 truncate">{user?.email}</p>
                    </div>
                  </div>
                  <button
                    onClick={handleLogout}
                    className="flex items-center gap-3 px-4 py-3 rounded-xl text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 transition"
                  >
                    <Icons.Logout />
                    Keluar
                  </button>
                </>
              )}
            </nav>
          </div>
        </div>
      )}
    </>
  )
}

export default Header
