// frontend/counsela/src/pages/ClientDashboard.jsx
import { useEffect, useState } from "react"
import { Link } from "react-router-dom"
import useAuth from "../hooks/useAuth"
import api from "../utils/axios"
import { toast } from "react-hot-toast"

const Icons = {
  Calendar: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
  ),
  Clock: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Money: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Message: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
    </svg>
  ),
  CheckCircle: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  ArrowRight: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
    </svg>
  ),
  Plus: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
    </svg>
  ),
  Loading: () => (
    <svg className="animate-spin h-5 w-5" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
    </svg>
  ),
}

const ClientDashboard = () => {
  const { user } = useAuth()
  const [consultations, setConsultations] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchMyConsultations = async () => {
      try {
        setLoading(true)
        const response = await api.get("/consultations/client")
        const data = response.data.data || []
        setConsultations(data)
      } catch (error) {
        console.error("Gagal load konsultasi:", error)
        toast.error("Gagal memuat data konsultasi")
      } finally {
        setLoading(false)
      }
    }
    fetchMyConsultations()
  }, [])

  const pendingOrders = consultations.filter(c => c.status === "pending")
  const acceptedOrders = consultations.filter(c => c.status === "accepted")
  const dpWaitingOrders = consultations.filter(c => c.dp_payment_status === "waiting_verification")
  const ongoingOrders = consultations.filter(c => c.status === "ongoing")
  const waitingPelunasanOrders = consultations.filter(c => c.status === "waiting_pelunasan")
  const completedOrders = consultations.filter(c => c.status === "completed")

  const getStatusBadge = (consultation) => {
    if (consultation.status === "pending") {
      return <span className="px-2 py-1 rounded-full text-xs bg-yellow-100 text-yellow-700">Menunggu Diterima</span>
    }
    if (consultation.status === "accepted" && consultation.dp_payment_status !== "paid") {
      return <span className="px-2 py-1 rounded-full text-xs bg-blue-100 text-blue-700">Menunggu DP</span>
    }
    if (consultation.dp_payment_status === "waiting_verification") {
      return <span className="px-2 py-1 rounded-full text-xs bg-yellow-100 text-yellow-700">Verifikasi DP</span>
    }
    if (consultation.dp_payment_status === "paid" && consultation.status === "accepted") {
      return <span className="px-2 py-1 rounded-full text-xs bg-green-100 text-green-700">DP Lunas</span>
    }
    if (consultation.status === "ongoing") {
      return <span className="px-2 py-1 rounded-full text-xs bg-purple-100 text-purple-700">Konsultasi Berjalan</span>
    }
    if (consultation.status === "waiting_pelunasan") {
      return <span className="px-2 py-1 rounded-full text-xs bg-orange-100 text-orange-700">Menunggu Pelunasan</span>
    }
    if (consultation.status === "completed") {
      return <span className="px-2 py-1 rounded-full text-xs bg-green-100 text-green-700">Selesai</span>
    }
    if (consultation.status === "cancelled") {
      return <span className="px-2 py-1 rounded-full text-xs bg-red-100 text-red-700">Dibatalkan</span>
    }
    return <span className="px-2 py-1 rounded-full text-xs bg-gray-100 text-gray-700">{consultation.status}</span>
  }

  const stats = [
    { label: "Menunggu", value: pendingOrders.length + acceptedOrders.length, icon: Icons.Clock, color: "yellow" },
    { label: "Verifikasi DP", value: dpWaitingOrders.length, icon: Icons.Money, color: "blue" },
    { label: "Konsultasi", value: ongoingOrders.length, icon: Icons.Message, color: "purple" },
    { label: "Selesai", value: completedOrders.length, icon: Icons.CheckCircle, color: "green" }, // ← "Selesai" bukan "Kelaar"
  ]

  const statColors = {
    yellow: "bg-yellow-100 text-yellow-600 dark:bg-yellow-900/30 dark:text-yellow-400",
    blue: "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400",
    purple: "bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400",
    green: "bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400",
  }

  return (
    <div>
      {/* Hero Client */}
      <div className="bg-gradient-to-r from-teal-600 to-emerald-600 rounded-2xl p-6 text-white mb-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-2xl font-bold">Selamat Datang, {user?.nama} 👋</h1>
            <p className="text-teal-100 mt-1">Kelola konsultasi hukum Anda di sini</p>
          </div>
          <Link 
            to="/consultation/new" 
            className="inline-flex items-center gap-2 bg-white text-teal-600 px-5 py-2 rounded-xl font-semibold hover:shadow-lg transition text-sm"
          >
            <Icons.Plus /> Booking Konsultasi
          </Link>
        </div>
      </div>

      {/* Statistik */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {stats.map((stat, idx) => {
          const Icon = stat.icon
          return (
            <div key={idx} className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center shadow-md hover:shadow-lg transition">
              <div className={`w-10 h-10 mx-auto rounded-full flex items-center justify-center mb-2 ${statColors[stat.color]}`}>
                <Icon />
              </div>
              <p className="text-2xl font-bold text-gray-800 dark:text-white">{stat.value}</p>
              <p className="text-xs text-gray-500">{stat.label}</p>
            </div>
          )
        })}
      </div>

      {/* Loading */}
      {loading && (
        <div className="flex justify-center items-center py-12">
          <Icons.Loading />
          <span className="ml-2 text-gray-500">Memuat data konsultasi...</span>
        </div>
      )}

      {/* Daftar Konsultasi */}
      {!loading && consultations.length > 0 && (
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-md overflow-hidden">
          <div className="p-5 border-b border-gray-200 dark:border-gray-700">
            <h2 className="text-lg font-bold text-gray-800 dark:text-white">📋 Daftar Konsultasi</h2>
          </div>
          <div className="divide-y divide-gray-200 dark:divide-gray-700">
            {consultations.map((c) => (
              <div key={c.id} className="p-4 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition">
                <div className="flex flex-col md:flex-row md:justify-between md:items-center gap-3">
                  <div className="flex-1">
                    <p className="font-semibold text-gray-800 dark:text-white">{c.judul_kasus}</p>
                    <div className="flex flex-wrap gap-3 mt-1 text-sm text-gray-500">
                      <span className="flex items-center gap-1">
                        <Icons.Calendar /> {c.tanggal_konsultasi?.split('T')[0]}
                      </span>
                      <span className="flex items-center gap-1">
                        <Icons.Clock /> {c.jam_konsultasi}
                      </span>
                      <span className="text-gray-400">Lawyer: {c.lawyer_name}</span>
                    </div>
                    {c.meeting_link && (
                      <a href={c.meeting_link} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-green-600 text-sm mt-2 hover:underline">
                        🔗 Join Meeting
                      </a>
                    )}
                  </div>
                  <div className="flex flex-col items-start md:items-end gap-2">
                    {getStatusBadge(c)}
                    <Link 
                      to={`/consultations/${c.id}`} 
                      className="text-blue-600 text-sm hover:underline inline-flex items-center gap-1"
                    >
                      Lihat Detail <Icons.ArrowRight />
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Empty State */}
      {!loading && consultations.length === 0 && (
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-md p-8 text-center">
          <div className="w-16 h-16 mx-auto bg-gray-100 dark:bg-gray-700 rounded-full flex items-center justify-center mb-4">
            <Icons.Message />
          </div>
          <p className="text-gray-500">Belum ada konsultasi</p>
          <Link to="/consultation/new" className="text-teal-600 mt-2 inline-block text-sm hover:underline">
            Booking sekarang →
          </Link>
        </div>
      )}
    </div>
  )
}

export default ClientDashboard

// frontend/counsela/src/pages/ClientDashboard.vue
<template>
  <div class="space-y-8 text-zinc-950">
    <!-- {Header} -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 border-b border-zinc-200">
      <div>
        <div class="text-xs font-semibold text-zinc-500 tracking-wide">
          Portal Klien
        </div>
        <h1 class="text-3xl font-bold tracking-tight text-zinc-950 mt-1">
          Dashboard Klien
        </h1>
        <p class="text-xs text-zinc-500 mt-1">
          Selamat datang, <span class="font-bold text-zinc-900">{{ user?.nama }}</span>. Pantau jadwal dan status konsultasi hukum Anda.
        </p>
      </div>

      <RouterLink
        to="/consultation/new"
        class="px-5 py-2.5 text-xs font-semibold bg-black hover:bg-zinc-800 text-white rounded-full shadow-sm transition-all inline-flex items-center gap-2"
      >
        <Plus class="w-3.5 h-3.5" />
        <span>Jadwalkan Konsultasi Baru</span>
      </RouterLink>
    </div>

    <!-- {Active Consultation} -->
    <div
      v-if="activeConsultation"
      class="p-6 rounded-3xl border border-zinc-200 bg-zinc-50/70 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 shadow-sm"
    >
      <div class="space-y-1">
        <div class="flex items-center gap-2">
          <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
          <span class="text-xs font-semibold text-zinc-800">
            Sesi Konsultasi Aktif
          </span>
        </div>
        <h3 class="font-bold text-base text-zinc-950 tracking-tight">
          {{ activeConsultation.judul_kasus }}
        </h3>
        <p class="text-xs text-zinc-600">
          Bersama {{ activeConsultation.lawyer_name }} • <span class="font-mono">{{ activeConsultation.tanggal_konsultasi?.split('T')[0] }} ({{ activeConsultation.jam_konsultasi }} WIB)</span>
        </p>
      </div>

      <div class="flex items-center gap-2 w-full sm:w-auto">
        <a
          v-if="activeConsultation.meeting_link && activeConsultation.status === 'ongoing'"
          :href="activeConsultation.meeting_link"
          target="_blank"
          rel="noopener noreferrer"
          class="flex-1 sm:flex-initial inline-flex items-center justify-center gap-1.5 px-4 py-2 text-xs font-semibold bg-emerald-700 hover:bg-emerald-800 text-white rounded-full transition-colors shadow-2xs text-center"
        >
          <Video class="w-3.5 h-3.5" />
          <span>Masuk Ruang Rapat</span>
        </a>
        <RouterLink
          :to="`/consultations/${activeConsultation.id}`"
          class="flex-1 sm:flex-initial inline-flex items-center justify-center gap-1.5 px-4 py-2 text-xs font-semibold bg-white border border-zinc-300 hover:bg-zinc-100 text-zinc-900 rounded-full transition-colors text-center"
        >
          <span>Lihat Detail</span>
          <ArrowRight class="w-3.5 h-3.5" />
        </RouterLink>
      </div>
    </div>

    <!-- {Metrics} -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <div
        v-for="(item, idx) in stats"
        :key="idx"
        class="p-5 bg-white border border-zinc-200/90 rounded-2xl shadow-2xs space-y-1.5 hover:border-zinc-300 transition-colors"
      >
        <span class="text-xs font-medium text-zinc-500 block">
          {{ item.label }}
        </span>
        <span class="text-3xl font-bold tracking-tight block" :class="item.color">
          {{ item.count }}
        </span>
      </div>
    </div>

    <!-- {Consultations} -->
    <div class="bg-white border border-zinc-200/90 rounded-3xl shadow-sm overflow-hidden">
      <div class="px-6 py-5 border-b border-zinc-200 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
        <div>
          <h2 class="text-base font-bold text-zinc-950 tracking-tight">
            Daftar Konsultasi
          </h2>
          <p class="text-xs text-zinc-500">Riwayat jadwal konsultasi hukum Anda</p>
        </div>
        <span class="text-xs font-medium text-zinc-600 bg-zinc-100 px-3 py-1 rounded-full border border-zinc-200">
          Total <strong class="text-zinc-900 font-semibold">{{ consultations.length }}</strong> Kasus
        </span>
      </div>

      <div v-if="loading" class="p-12 text-center text-xs text-zinc-400 font-sans">
        Memuat data perkara...
      </div>

      <div
        v-else-if="consultations.length === 0"
        class="p-16 text-center text-xs text-zinc-500 space-y-3"
      >
        <p class="text-base font-bold text-zinc-900">Belum ada riwayat konsultasi</p>
        <p class="max-w-sm mx-auto">
          Mulai konsultasi dengan advokat terverifikasi untuk mendapatkan solusi hukum yang tepat.
        </p>
        <RouterLink to="/consultation/new" class="inline-flex items-center gap-1.5 px-5 py-2.5 text-xs font-semibold bg-black text-white rounded-full hover:bg-zinc-800 transition-colors">
          <span>Buat Jadwal Pertama Anda</span>
          <ArrowRight class="w-3.5 h-3.5" />
        </RouterLink>
      </div>

      <div v-else class="overflow-x-auto">
        <table class="w-full text-left text-xs sm:text-sm">
          <thead class="bg-zinc-50 text-zinc-500 text-xs font-medium border-b border-zinc-200">
            <tr>
              <th class="px-6 py-3.5">No. Konsultasi</th>
              <th class="px-6 py-3.5">Pokok Kasus</th>
              <th class="px-6 py-3.5">Advokat</th>
              <th class="px-6 py-3.5">Waktu Sesi</th>
              <th class="px-6 py-3.5">Status</th>
              <th class="px-6 py-3.5 text-right">Aksi</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-zinc-100 text-zinc-700">
            <tr
              v-for="item in consultations"
              :key="item.id"
              class="hover:bg-zinc-50/70 transition-colors"
            >
              <td class="px-6 py-4 font-mono text-xs text-zinc-500 font-medium whitespace-nowrap">
                #CNS-{{ String(item.id).padStart(4, '0') }}
              </td>
              <td class="px-6 py-4 font-semibold text-zinc-950 max-w-xs truncate">
                {{ item.judul_kasus }}
              </td>
              <td class="px-6 py-4 text-zinc-600 truncate max-w-[160px]">
                {{ item.lawyer_name || '-' }}
              </td>
              <td class="px-6 py-4 text-xs font-mono whitespace-nowrap">
                {{ item.tanggal_konsultasi?.split('T')[0] }} • {{ item.jam_konsultasi }} WIB
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span :class="getStatusBadge(item.status)">
                  {{ item.status?.replace('_', ' ') }}
                </span>
              </td>
              <td class="px-6 py-4 text-right whitespace-nowrap space-x-2">
                <a
                  v-if="item.meeting_link && item.status === 'ongoing'"
                  :href="item.meeting_link"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold bg-emerald-700 hover:bg-emerald-800 text-white rounded-full transition-colors shadow-2xs"
                >
                  <Video class="w-3 h-3" />
                  <span>Rapat</span>
                </a>
                <RouterLink
                  :to="`/consultations/${item.id}`"
                  class="inline-flex items-center gap-1 px-3.5 py-1.5 text-xs font-semibold bg-zinc-100 hover:bg-zinc-200 text-zinc-900 rounded-full transition-colors"
                >
                  <FileText class="w-3 h-3" />
                  <span>Detail</span>
                </RouterLink>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { Plus, ArrowRight, Video, FileText } from '@lucide/vue'
import { useAuth } from '../composables/useAuth'
import api from '../utils/axios'
import { toast } from '../composables/useToast'

const { user } = useAuth()

const consultations = ref([])
const loading = ref(true)

const fetchConsultations = async () => {
  try {
    loading.value = true
    const res = await api.get('/consultations/client')
    consultations.value = res.data.data || []
  } catch {
    toast.error('Gagal memuat konsultasi')
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchConsultations()
})

const activeConsultation = computed(() => {
  return consultations.value.find(
    (c) => c.status === 'ongoing' || (c.status === 'accepted' && c.dp_payment_status === 'paid')
  )
})

const stats = computed(() => [
  {
    label: 'Menunggu Konfirmasi',
    count: consultations.value.filter((c) => c.status === 'pending' || c.status === 'accepted').length,
    color: 'text-amber-700',
  },
  {
    label: 'Konsultasi Berjalan',
    count: consultations.value.filter((c) => c.status === 'ongoing').length,
    color: 'text-blue-700',
  },
  {
    label: 'Menunggu Pelunasan',
    count: consultations.value.filter((c) => c.status === 'waiting_pelunasan').length,
    color: 'text-orange-700',
  },
  {
    label: 'Perkara Selesai',
    count: consultations.value.filter((c) => c.status === 'completed').length,
    color: 'text-emerald-700',
  },
])

const getStatusBadge = (status) => {
  const map = {
    pending: 'text-amber-800 bg-amber-50 border-amber-200',
    accepted: 'text-blue-800 bg-blue-50 border-blue-200',
    ongoing: 'text-indigo-800 bg-indigo-50 border-indigo-200',
    waiting_pelunasan: 'text-orange-800 bg-orange-50 border-orange-200',
    completed: 'text-emerald-800 bg-emerald-50 border-emerald-200',
    cancelled: 'text-slate-600 bg-slate-100 border-slate-200',
  }
  return `inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-medium border ${map[status?.toLowerCase()] || map.cancelled}`
}
</script>
