// frontend/counsela/src/pages/ConsultationDetails.jsx
import { useEffect, useState } from "react"
import { useParams, Link, useSearchParams } from "react-router-dom"
import api from "../utils/axios"
import { toast } from "react-hot-toast"
import ReviewModal from "../components/ReviewModal"

const Icons = {
  ArrowLeft: () => (
    <svg className="w-4 h-4 group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 18l-6-6 6-6" />
    </svg>
  ),
  Calendar: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
  ),
  Clock: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  User: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
    </svg>
  ),
  Lawyer: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
    </svg>
  ),
  Money: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Description: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 6h16M4 12h16M4 18h16" />
    </svg>
  ),
  Video: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
    </svg>
  ),
  CheckCircle: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Upload: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
    </svg>
  ),
  Loading: () => (
    <svg className="animate-spin h-5 w-5" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
    </svg>
  ),
}

const ConsultationDetail = () => {
  const { id } = useParams()
  const [searchParams] = useSearchParams()
  const [consultation, setConsultation] = useState(null)
  const [loading, setLoading] = useState(true)
  const [showReviewModal, setShowReviewModal] = useState(false)
  const [showDpModal, setShowDpModal] = useState(false)
  const [showFinalModal, setShowFinalModal] = useState(false)
  const [dpFile, setDpFile] = useState(null)
  const [finalFile, setFinalFile] = useState(null)
  const [submitting, setSubmitting] = useState(false)

  const shouldOpenReview = searchParams.get("review") === "true"

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true)
        const response = await api.get(`/consultations/${id}`)
        const data = response.data.data || response.data
        setConsultation(data)
      } catch (err) { 
        console.error(err)
        toast.error("Gagal memuat data") 
      } finally { 
        setLoading(false) 
      }
    }
    fetchData()
  }, [id])

  useEffect(() => {
    if (shouldOpenReview && consultation?.status === "completed") {
      setShowReviewModal(true)
    }
  }, [shouldOpenReview, consultation])

  const handleUploadDp = async () => {
    if (!dpFile) {
      toast.error("Pilih file bukti transfer DP")
      return
    }
    setSubmitting(true)
    const formData = new FormData()
    formData.append("dp_proof", dpFile)
    formData.append("consultation_id", consultation.id)
    try {
      await api.post("/consultations/upload-dp", formData, {
        headers: { "Content-Type": "multipart/form-data" }
      })
      toast.success("Bukti DP terkirim, menunggu verifikasi admin")
      setShowDpModal(false)
      setDpFile(null)
      window.location.reload()
    } catch (error) {
      toast.error("Gagal mengirim bukti DP")
    } finally {
      setSubmitting(false)
    }
  }

  const handleUploadFinal = async () => {
    if (!finalFile) {
      toast.error("Pilih file bukti pelunasan")
      return
    }
    setSubmitting(true)
    const formData = new FormData()
    formData.append("final_payment_proof", finalFile)
    formData.append("consultation_id", consultation.id)
    try {
      await api.post("/consultations/upload-final-payment", formData, {
        headers: { "Content-Type": "multipart/form-data" }
      })
      toast.success("Bukti pelunasan terkirim, menunggu verifikasi admin")
      setShowFinalModal(false)
      setFinalFile(null)
      window.location.reload()
    } catch (error) {
      toast.error("Gagal mengirim bukti pelunasan")
    } finally {
      setSubmitting(false)
    }
  }

  const formatDate = (date) => {
    if (!date) return "-"
    const d = new Date(date)
    return d.toLocaleDateString('id-ID', { year: 'numeric', month: 'long', day: 'numeric' })
  }

  const formatCurrency = (amount) => {
    return `Rp ${(amount || 0).toLocaleString("id-ID")}`
  }

  const getStatusDisplay = () => {
    const c = consultation
    if (!c) return { text: "", color: "", icon: null }
    if (c.status === "pending") return { text: "Menunggu Diterima Lawyer", color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400", icon: "⏳" }
    if (c.status === "accepted" && c.dp_payment_status !== "paid") return { text: "Menunggu Pembayaran DP", color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400", icon: "💰" }
    if (c.dp_payment_status === "waiting_verification") return { text: "Verifikasi DP", color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400", icon: "⏳" }
    if (c.dp_payment_status === "paid" && c.status === "accepted") return { text: "DP Lunas, Menunggu Meeting Link", color: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400", icon: "✅" }
    if (c.status === "ongoing") return { text: "Konsultasi Berjalan", color: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400", icon: "💬" }
    if (c.status === "waiting_pelunasan") return { text: "Menunggu Pelunasan", color: "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400", icon: "💳" }
    if (c.final_payment_status === "waiting_verification") return { text: "Verifikasi Pelunasan", color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400", icon: "⏳" }
    if (c.status === "completed") return { text: "Selesai", color: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400", icon: "✅" }
    if (c.status === "cancelled") return { text: "Dibatalkan", color: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400", icon: "❌" }
    return { text: c.status, color: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400", icon: "📋" }
  }

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <Icons.Loading />
        <span className="ml-2 text-gray-500">Memuat detail konsultasi...</span>
      </div>
    )
  }

  if (!consultation) {
    return (
      <div className="text-center py-20">
        <div className="w-20 h-20 mx-auto bg-gray-100 dark:bg-gray-800 rounded-full flex items-center justify-center mb-4 text-4xl">
          😞
        </div>
        <h2 className="text-2xl font-bold text-gray-800 dark:text-white">Konsultasi tidak ditemukan</h2>
        <Link to="/consultations" className="inline-flex items-center gap-2 mt-6 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl transition">
          Kembali
        </Link>
      </div>
    )
  }

  const statusDisplay = getStatusDisplay()
  const dpAmount = Math.floor((consultation.tarif_konsultasi || 0) / 2)
  const sisaAmount = (consultation.tarif_konsultasi || 0) - dpAmount

  return (
    <div className="max-w-4xl mx-auto">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-700 to-indigo-800 rounded-2xl p-6 text-white mb-6">
        <Link to="/consultations" className="inline-flex items-center gap-2 text-white/80 hover:text-white mb-4 transition group">
          <Icons.ArrowLeft /> Kembali
        </Link>
        <h1 className="text-2xl font-bold">Detail Konsultasi</h1>
        <p className="text-blue-100 mt-1">Informasi lengkap tentang konsultasi hukum Anda</p>
      </div>

      {/* Card Detail */}
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg overflow-hidden">
        {/* Header Status */}
        <div className="p-5 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center flex-wrap gap-3">
          <div className="flex items-center gap-2">
            <span className="text-2xl">{statusDisplay.icon}</span>
            <div>
              <span className="text-sm text-gray-500 dark:text-gray-400">Status</span>
              <div className="mt-1">
                <span className={`px-3 py-1 rounded-full text-sm ${statusDisplay.color}`}>{statusDisplay.text}</span>
              </div>
            </div>
          </div>
          {consultation.meeting_link && (
            <a href={consultation.meeting_link} target="_blank" rel="noreferrer" className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-xl text-sm flex items-center gap-2 transition">
              <Icons.Video /> Join Meeting
            </a>
          )}
        </div>

        <div className="p-6 space-y-6">
          <h2 className="text-xl font-bold text-gray-800 dark:text-white">{consultation.judul_kasus}</h2>

          <div className="grid md:grid-cols-2 gap-4">
            <div className="bg-gray-50 dark:bg-gray-900 p-4 rounded-xl">
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400 mb-1">
                <Icons.User /> Client
              </div>
              <p className="font-semibold text-gray-800 dark:text-white mt-1">{consultation.client_name || "Client"}</p>
            </div>
            <div className="bg-gray-50 dark:bg-gray-900 p-4 rounded-xl">
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400 mb-1">
                <Icons.Lawyer /> Lawyer
              </div>
              <p className="font-semibold text-gray-800 dark:text-white mt-1">{consultation.lawyer_name || "Lawyer"}</p>
            </div>
            <div className="bg-gray-50 dark:bg-gray-900 p-4 rounded-xl">
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400 mb-1">
                <Icons.Calendar /> Tanggal
              </div>
              <p className="font-semibold text-gray-800 dark:text-white mt-1">{formatDate(consultation.tanggal_konsultasi)}</p>
            </div>
            <div className="bg-gray-50 dark:bg-gray-900 p-4 rounded-xl">
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400 mb-1">
                <Icons.Clock /> Jam
              </div>
              <p className="font-semibold text-gray-800 dark:text-white mt-1">{consultation.jam_konsultasi}</p>
            </div>
          </div>

          <div className="bg-gray-50 dark:bg-gray-900 p-5 rounded-xl">
            <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400 mb-2">
              <Icons.Description /> Deskripsi Kasus
            </div>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{consultation.deskripsi_kasus || "Tidak ada deskripsi"}</p>
          </div>

          <div className="bg-gray-50 dark:bg-gray-800 p-5 rounded-xl border border-gray-200 dark:border-gray-700">
            <h3 className="font-semibold text-gray-800 dark:text-white mb-3 flex items-center gap-2">
              <Icons.Money /> Rincian Pembayaran
            </h3>
            <div className="space-y-2">
              <div className="flex justify-between py-2 border-b border-gray-200 dark:border-gray-700">
                <span className="text-gray-600 dark:text-gray-400">Total Tarif</span>
                <span className="font-bold text-gray-800 dark:text-white">{formatCurrency(consultation.tarif_konsultasi)}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-200 dark:border-gray-700">
                <span className="text-gray-600 dark:text-gray-400">DP (50%)</span>
                <span className="font-bold text-blue-600 dark:text-blue-400">{formatCurrency(dpAmount)}</span>
              </div>
              <div className="flex justify-between py-2">
                <span className="text-gray-600 dark:text-gray-400">Sisa Pelunasan (50%)</span>
                <span className="font-bold text-orange-600 dark:text-orange-400">{formatCurrency(sisaAmount)}</span>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          {consultation.status === "accepted" && consultation.dp_payment_status !== "paid" && consultation.dp_payment_status !== "waiting_verification" && (
            <button onClick={() => setShowDpModal(true)} className="w-full bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-xl font-semibold transition flex items-center justify-center gap-2">
              <Icons.Money /> Bayar DP (50%)
            </button>
          )}

          {consultation.dp_payment_status === "waiting_verification" && (
            <div className="p-4 bg-yellow-50 dark:bg-yellow-900/20 rounded-xl text-center flex items-center justify-center gap-2">
              <Icons.Loading /> <span className="text-yellow-600 dark:text-yellow-400">Bukti DP sedang diverifikasi admin</span>
            </div>
          )}

          {consultation.dp_payment_status === "paid" && consultation.status === "accepted" && (
            <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-xl text-center">
              <p className="text-green-600 dark:text-green-400 flex items-center justify-center gap-2">
                <Icons.CheckCircle /> DP sudah lunas. Menunggu lawyer memberikan meeting link.
              </p>
            </div>
          )}

          {consultation.status === "waiting_pelunasan" && consultation.final_payment_status !== "paid" && consultation.final_payment_status !== "waiting_verification" && (
            <button onClick={() => setShowFinalModal(true)} className="w-full bg-orange-600 hover:bg-orange-700 text-white py-3 rounded-xl font-semibold transition flex items-center justify-center gap-2">
              <Icons.Money /> Bayar Pelunasan (50%)
            </button>
          )}

          {consultation.final_payment_status === "waiting_verification" && (
            <div className="p-4 bg-yellow-50 dark:bg-yellow-900/20 rounded-xl text-center">
              <p className="text-yellow-600 dark:text-yellow-400 flex items-center justify-center gap-2">
                <Icons.Loading /> Bukti pelunasan sedang diverifikasi admin
              </p>
            </div>
          )}

          {consultation.status === "completed" && (
            <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-xl text-center">
              <p className="text-green-600 dark:text-green-400 flex items-center justify-center gap-2">
                <Icons.CheckCircle /> Konsultasi selesai! Terima kasih telah menggunakan Counsela.
              </p>
            </div>
          )}

          {consultation.status === "cancelled" && (
            <div className="p-4 bg-red-50 dark:bg-red-900/20 rounded-xl text-center">
              <p className="text-red-600 dark:text-red-400">❌ Konsultasi dibatalkan</p>
            </div>
          )}

          <div className="text-xs text-gray-400 dark:text-gray-500 border-t border-gray-200 dark:border-gray-700 pt-4">
            <p>ID Konsultasi: {consultation.id}</p>
            <p>Dibuat: {new Date(consultation.created_at).toLocaleString('id-ID')}</p>
          </div>
        </div>

        <div className="p-5 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900/50">
          <Link to="/consultations" className="inline-flex items-center gap-2 text-gray-600 hover:text-blue-600 dark:text-gray-400 dark:hover:text-blue-400 transition group">
            <Icons.ArrowLeft /> Kembali ke Daftar Konsultasi
          </Link>
        </div>
      </div>

      {/* Modal Upload DP - DIPERBAIKI */}
      {showDpModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 w-full max-w-md shadow-2xl">
            <div className="text-center mb-4">
              <div className="text-4xl mb-2">💰</div>
              <h3 className="text-xl font-bold text-gray-800 dark:text-white">Bayar DP (50%)</h3>
              <p className="text-sm text-gray-600 dark:text-gray-300 mt-1">Transfer ke rekening:</p>
              <p className="font-bold text-gray-800 dark:text-white">BCA - 1234567890</p>
              <p className="text-sm text-gray-600 dark:text-gray-300">a.n. PT Counsela Indonesia</p>
            </div>

            <div className="space-y-3 mb-4">
              <div className="flex justify-between py-2 border-b border-gray-200 dark:border-gray-700">
                <span className="text-gray-600 dark:text-gray-300">Total Tarif</span>
                <span className="font-bold text-gray-800 dark:text-white">{formatCurrency(consultation.tarif_konsultasi)}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-200 dark:border-gray-700">
                <span className="text-gray-600 dark:text-gray-300">DP (50%)</span>
                <span className="font-bold text-blue-600 dark:text-blue-400">{formatCurrency(dpAmount)}</span>
              </div>
              <div className="flex justify-between py-2">
                <span className="text-gray-600 dark:text-gray-300">Sisa Pelunasan (50%)</span>
                <span className="font-bold text-gray-500 dark:text-gray-400">{formatCurrency(sisaAmount)}</span>
              </div>
            </div>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Upload Bukti Transfer DP</label>
              <input 
                type="file" 
                accept="image/*,application/pdf"
                onChange={(e) => setDpFile(e.target.files[0])} 
                className="w-full p-3 rounded-xl border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-blue-50 file:text-blue-700 dark:file:bg-blue-900/30 dark:file:text-blue-400 hover:file:bg-blue-100 dark:hover:file:bg-blue-900/50"
              />
              <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">Format: JPG, PNG, PDF (max 2MB)</p>
            </div>

            <div className="flex gap-3">
              <button onClick={handleUploadDp} disabled={submitting} className="flex-1 bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-xl font-semibold transition flex items-center justify-center gap-2 disabled:opacity-50">
                {submitting ? <Icons.Loading /> : <Icons.Upload />} {submitting ? "Mengirim..." : "Kirim Bukti"}
              </button>
              <button onClick={() => setShowDpModal(false)} className="flex-1 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-white py-3 rounded-xl font-semibold hover:bg-gray-300 dark:hover:bg-gray-600 transition">
                Batal
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Modal Upload Pelunasan - DIPERBAIKI */}
      {showFinalModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 w-full max-w-md shadow-2xl">
            <div className="text-center mb-4">
              <div className="text-4xl mb-2">💳</div>
              <h3 className="text-xl font-bold text-gray-800 dark:text-white">Bayar Pelunasan (50%)</h3>
              <p className="text-sm text-gray-600 dark:text-gray-300 mt-1">Transfer ke rekening:</p>
              <p className="font-bold text-gray-800 dark:text-white">BCA - 1234567890</p>
              <p className="text-sm text-gray-600 dark:text-gray-300">a.n. PT Counsela Indonesia</p>
            </div>

            <div className="space-y-3 mb-4">
              <div className="flex justify-between py-2 border-b border-gray-200 dark:border-gray-700">
                <span className="text-gray-600 dark:text-gray-300">Sisa yang harus dibayar</span>
                <span className="font-bold text-blue-600 dark:text-blue-400">{formatCurrency(sisaAmount)}</span>
              </div>
            </div>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Upload Bukti Pelunasan</label>
              <input 
                type="file" 
                accept="image/*,application/pdf"
                onChange={(e) => setFinalFile(e.target.files[0])} 
                className="w-full p-3 rounded-xl border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-green-50 file:text-green-700 dark:file:bg-green-900/30 dark:file:text-green-400 hover:file:bg-green-100 dark:hover:file:bg-green-900/50"
              />
              <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">Format: JPG, PNG, PDF (max 2MB)</p>
            </div>

            <div className="flex gap-3">
              <button onClick={handleUploadFinal} disabled={submitting} className="flex-1 bg-green-600 hover:bg-green-700 text-white py-3 rounded-xl font-semibold transition flex items-center justify-center gap-2 disabled:opacity-50">
                {submitting ? <Icons.Loading /> : <Icons.Upload />} {submitting ? "Mengirim..." : "Kirim Bukti"}
              </button>
              <button onClick={() => setShowFinalModal(false)} className="flex-1 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-white py-3 rounded-xl font-semibold hover:bg-gray-300 dark:hover:bg-gray-600 transition">
                Batal
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Modal Review */}
      {showReviewModal && (
        <ReviewModal 
          consultation={consultation} 
          onClose={() => setShowReviewModal(false)} 
          onSuccess={() => window.location.reload()} 
        />
      )}
    </div>
  )
}

export default ConsultationDetail

// frontend/counsela/src/pages/ConsultationDetails.vue
<template>
  <div class="max-w-4xl mx-auto space-y-6 text-zinc-950">
    <!-- {Header} -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 pb-4 border-b border-zinc-200/90 print:hidden">
      <div>
        <RouterLink
          to="/consultations"
          class="text-xs font-medium text-zinc-500 hover:text-black transition-colors inline-flex items-center gap-1.5"
        >
          <ArrowLeft class="w-3.5 h-3.5" />
          <span>Kembali ke Daftar Konsultasi</span>
        </RouterLink>
        <div class="text-xs font-semibold text-zinc-500 tracking-wide mt-1">
          Rincian Konsultasi
        </div>
        <h1 class="text-2xl sm:text-3xl font-bold tracking-tight text-zinc-950 mt-0.5 flex items-center gap-3">
          <span>Perkara #CNS-{{ String(id).padStart(4, '0') }}</span>
        </h1>
      </div>

      <div class="flex items-center gap-2">
        <button
          @click="printDocket"
          class="px-3.5 py-1.5 rounded-full border border-zinc-200 hover:bg-zinc-50 text-xs font-medium text-zinc-700 transition-colors flex items-center gap-1.5 cursor-pointer"
          title="Cetak Berkas"
        >
          <Printer class="w-3.5 h-3.5 text-zinc-600" />
          <span>Cetak Berkas</span>
        </button>
        <span v-if="consultation" :class="statusBadgeClass">
          {{ consultation.status?.replace('_', ' ') }}
        </span>
      </div>
    </div>

    <!-- {Loading} -->
    <div v-if="loading" class="p-16 text-center text-xs text-zinc-400 font-sans">
      Memuat rincian berkas perkara...
    </div>

    <!-- {Not Found} -->
    <div
      v-else-if="!consultation"
      class="p-16 text-center space-y-3 bg-white border border-zinc-200 rounded-3xl"
    >
      <p class="text-lg font-bold text-zinc-900">Data Konsultasi Tidak Ditemukan</p>
      <RouterLink to="/consultations" class="text-xs font-semibold text-black hover:underline">
        Kembali ke Daftar Konsultasi
      </RouterLink>
    </div>

    <!-- {Content} -->
    <template v-else>
      <!-- {Tracker} -->
      <div class="p-4 bg-white border border-zinc-200 rounded-2xl shadow-2xs overflow-x-auto print:hidden">
        <div class="flex items-center justify-between min-w-[550px] text-xs">
          <div
            v-for="(step, idx) in progressSteps"
            :key="idx"
            class="flex items-center gap-2"
          >
            <div
              class="w-6 h-6 rounded-full flex items-center justify-center font-bold text-[10px] shrink-0"
              :class="step.active
                ? 'bg-black text-white'
                : 'bg-zinc-100 text-zinc-400 border border-zinc-200'"
            >
              <Check v-if="step.done" class="w-3.5 h-3.5 stroke-[2.5]" />
              <span v-else>{{ idx + 1 }}</span>
            </div>
            <span
              class="text-[11px]"
              :class="step.active ? 'font-semibold text-zinc-950' : 'text-zinc-400'"
            >
              {{ step.label }}
            </span>
            <ChevronRight v-if="idx < progressSteps.length - 1" class="w-3.5 h-3.5 text-zinc-300 mx-1 shrink-0" />
          </div>
        </div>
      </div>

      <!-- {Details} -->
      <div class="bg-white border border-zinc-200 rounded-3xl p-6 sm:p-8 shadow-sm space-y-7 print:border-none print:shadow-none print:p-0">
        <!-- {Print Header} -->
        <div class="hidden print:block border-b-2 border-black pb-4 mb-6">
          <div class="flex items-center justify-between">
            <div>
              <h1 class="text-2xl font-bold tracking-tight">COUNSELA LEGAL TECH</h1>
              <p class="text-xs text-zinc-500">Lembar Konsultasi Hukum</p>
            </div>
            <div class="text-right text-xs">
              <p class="font-mono">NO: CNS-{{ String(id).padStart(4, '0') }}</p>
            </div>
          </div>
        </div>

        <!-- {Metadata} -->
        <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-2xl bg-zinc-50 border border-zinc-200 text-xs">
          <div>
            <span class="text-zinc-500 block text-[11px] font-medium">Klien</span>
            <span class="font-bold text-zinc-900 text-xs sm:text-sm mt-0.5 block truncate">
              {{ consultation.client_name || '-' }}
            </span>
          </div>
          <div>
            <span class="text-zinc-500 block text-[11px] font-medium">Advokat</span>
            <span class="font-bold text-zinc-900 text-xs sm:text-sm mt-0.5 block truncate">
              {{ consultation.lawyer_name || '-' }}
            </span>
          </div>
          <div>
            <span class="text-zinc-500 block text-[11px] font-medium">Jadwal Sesi</span>
            <span class="font-bold text-zinc-900 text-xs sm:text-sm mt-0.5 block font-mono">
              {{ consultation.tanggal_konsultasi?.split('T')[0] }}
            </span>
          </div>
          <div>
            <span class="text-zinc-500 block text-[11px] font-medium">Waktu</span>
            <span class="font-bold text-zinc-900 text-xs sm:text-sm mt-0.5 block font-mono">
              {{ consultation.jam_konsultasi }} WIB
            </span>
          </div>
        </div>

        <!-- {Subject} -->
        <div class="space-y-2">
          <div class="text-xs font-semibold text-zinc-500 tracking-wide">
            Pokok Masalah
          </div>
          <h2 class="text-xl sm:text-2xl font-bold text-zinc-950 leading-snug tracking-tight">
            {{ consultation.judul_kasus }}
          </h2>
          <div class="p-4 rounded-2xl bg-zinc-50 border border-zinc-200 text-xs sm:text-sm text-zinc-700 leading-relaxed whitespace-pre-line">
            {{ consultation.deskripsi_kasus }}
          </div>
        </div>

        <!-- {Meeting Room} -->
        <div
          v-if="consultation.meeting_link"
          class="p-5 rounded-2xl border border-emerald-200 bg-emerald-50/50 space-y-3 print:hidden"
        >
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <span class="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
              <h3 class="text-xs font-semibold text-emerald-950">
                Ruang Konsultasi Online
              </h3>
            </div>
            <span class="text-[11px] font-medium text-emerald-800 bg-emerald-100/80 px-2.5 py-0.5 rounded-full">
              Tautan Aktif
            </span>
          </div>

          <p class="text-xs text-emerald-900 leading-relaxed">
            Tautan konsultasi telah tersedia. Silakan bergabung tepat waktu sesuai jadwal yang disepakati.
          </p>

          <div class="flex flex-col sm:flex-row items-stretch sm:items-center gap-2 pt-1">
            <a
              :href="consultation.meeting_link"
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center justify-center gap-1.5 flex-1 text-center py-2.5 px-4 text-xs font-semibold bg-emerald-700 hover:bg-emerald-800 text-white rounded-full transition-colors shadow-2xs"
            >
              <span>Masuk ke Ruang Konsultasi</span>
              <ArrowRight class="w-3.5 h-3.5" />
            </a>
            <button
              @click="copyMeetingLink"
              class="py-2.5 px-4 text-xs font-medium border border-emerald-300 bg-white hover:bg-emerald-50 text-emerald-900 rounded-full transition-colors cursor-pointer"
            >
              Salin URL
            </button>
          </div>
        </div>

        <!-- {Billing} -->
        <div class="p-5 rounded-3xl border border-zinc-200 bg-white space-y-4">
          <div class="flex justify-between items-center border-b border-zinc-100 pb-3">
            <div>
              <h3 class="text-xs font-semibold text-zinc-900">
                Rincian Pembayaran
              </h3>
              <p class="text-[11px] text-zinc-500">Pembayaran DP 50% dan Pelunasan 50%</p>
            </div>
            <span class="font-mono text-xs font-bold text-zinc-900">
              Total: Rp {{ totalTarif.toLocaleString('id-ID') }}
            </span>
          </div>

          <div class="space-y-3 text-xs">
            <!-- {DP Row} -->
            <div class="p-3.5 rounded-2xl border border-zinc-200 bg-zinc-50 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
              <div>
                <span class="font-bold text-zinc-900 block">Tahap 1: Down Payment (50%)</span>
                <span class="text-[11px] text-zinc-500">Pembayaran awal untuk konfirmasi jadwal</span>
              </div>
              <div class="flex items-center gap-3">
                <span class="font-mono font-bold text-zinc-900 text-sm">
                  Rp {{ dpAmount.toLocaleString('id-ID') }}
                </span>
                <span
                  class="px-2.5 py-0.5 rounded-full text-[11px] font-medium border"
                  :class="consultation.dp_payment_status === 'paid'
                    ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                    : 'bg-zinc-100 text-zinc-600 border-zinc-200'"
                >
                  {{ consultation.dp_payment_status === 'paid' ? 'Lunas Terverifikasi' : 'Belum Dibayar' }}
                </span>
              </div>
            </div>

            <!-- {Pelunasan Row} -->
            <div class="p-3.5 rounded-2xl border border-zinc-200 bg-zinc-50 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
              <div>
                <span class="font-bold text-zinc-900 block">Tahap 2: Pelunasan (50%)</span>
                <span class="text-[11px] text-zinc-500">Pelunasan setelah sesi konsultasi selesai</span>
              </div>
              <div class="flex items-center gap-3">
                <span class="font-mono font-bold text-zinc-900 text-sm">
                  Rp {{ finalAmount.toLocaleString('id-ID') }}
                </span>
                <span
                  class="px-2.5 py-0.5 rounded-full text-[11px] font-medium border"
                  :class="consultation.final_payment_status === 'paid'
                    ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                    : 'bg-zinc-100 text-zinc-600 border-zinc-200'"
                >
                  {{ consultation.final_payment_status === 'paid' ? 'Lunas Terverifikasi' : 'Belum Dibayar' }}
                </span>
              </div>
            </div>
          </div>
        </div>

        <!-- {Actions} -->
        <div class="space-y-3 pt-2 print:hidden">
          <button
            v-if="consultation.status === 'accepted' && consultation.dp_payment_status !== 'paid'"
            @click="paymentType = 'dp'"
            class="w-full py-3.5 text-xs sm:text-sm font-semibold bg-black hover:bg-zinc-800 text-white rounded-full shadow-sm transition-all cursor-pointer"
          >
            Unggah Bukti Pembayaran DP (Rp {{ dpAmount.toLocaleString('id-ID') }})
          </button>

          <button
            v-if="consultation.status === 'waiting_pelunasan' && consultation.final_payment_status !== 'paid'"
            @click="paymentType = 'final'"
            class="w-full py-3.5 text-xs sm:text-sm font-semibold bg-black hover:bg-zinc-800 text-white rounded-full shadow-sm transition-all cursor-pointer"
          >
            Unggah Bukti Pelunasan (Rp {{ finalAmount.toLocaleString('id-ID') }})
          </button>

          <button
            v-if="consultation.status === 'completed'"
            @click="showReviewModal = true"
            class="w-full py-3.5 text-xs sm:text-sm font-semibold border border-zinc-300 hover:bg-zinc-50 text-zinc-900 rounded-full transition-all cursor-pointer"
          >
            Beri Penilaian & Ulasan Advokat
          </button>
        </div>
      </div>

      <!-- {Payment Modal} -->
      <div
        v-if="paymentType"
        class="fixed inset-0 bg-black/40 backdrop-blur-md flex items-center justify-center p-4 z-50 animate-in fade-in duration-100"
      >
        <form
          @submit.prevent="handleUploadProof"
          class="bg-white border border-zinc-200 rounded-3xl p-6 sm:p-7 w-full max-w-md space-y-4 shadow-xl text-sm"
        >
          <div>
            <div class="text-xs font-semibold text-zinc-500 tracking-wide">
              Pembayaran Konsultasi
            </div>
            <h3 class="font-bold text-lg text-zinc-950 mt-1">
              Unggah Bukti Transfer {{ paymentType === 'dp' ? 'DP 50%' : 'Pelunasan 50%' }}
            </h3>
            <p class="text-xs text-zinc-500 mt-1">
              Silakan transfer ke rekening resmi:
            </p>
            <div class="mt-2 p-3 rounded-2xl bg-zinc-50 border border-zinc-200 text-xs space-y-0.5">
              <p class="text-zinc-500">Bank: <span class="text-zinc-900 font-bold">BCA (Bank Central Asia)</span></p>
              <p class="text-zinc-500">No. Rekening: <span class="text-zinc-900 font-mono font-bold">1234567890</span></p>
              <p class="text-zinc-500">Atas Nama: <span class="text-zinc-900 font-bold">PT Counsela Legal Tech</span></p>
            </div>
          </div>

          <div>
            <label class="block text-xs font-semibold text-zinc-800 mb-1.5">
              Pilih Berkas Bukti Transfer (Foto / PDF)
            </label>
            <input
              type="file"
              accept="image/*,application/pdf"
              @change="(e) => proofFile = e.target.files[0]"
              class="w-full text-xs text-zinc-600 file:mr-3 file:py-2 file:px-3.5 file:rounded-full file:border-0 file:text-xs file:font-semibold file:bg-zinc-100 file:text-zinc-900 hover:file:bg-zinc-200 cursor-pointer border border-zinc-200 rounded-2xl p-1.5"
              required
            />
            <p v-if="proofFile" class="text-[11px] text-emerald-700 mt-1">
              Berkas dipilih: {{ proofFile.name }} ({{ (proofFile.size / 1024).toFixed(1) }} KB)
            </p>
          </div>

          <div class="flex justify-end gap-2 pt-3 border-t border-zinc-100">
            <button
              type="button"
              @click="paymentType = null; proofFile = null"
              class="px-4 py-2 text-xs font-semibold text-zinc-600 hover:text-black transition-colors cursor-pointer"
            >
              Batal
            </button>
            <button
              type="submit"
              :disabled="uploading || !proofFile"
              class="px-5 py-2 text-xs font-semibold bg-black hover:bg-zinc-800 text-white rounded-full transition-all disabled:opacity-40 shadow-sm cursor-pointer"
            >
              {{ uploading ? 'Mengunggah...' : 'Kirim Bukti Pembayaran' }}
            </button>
          </div>
        </form>
      </div>

      <!-- {Review Modal} -->
      <ReviewModal
        v-if="showReviewModal"
        :consultation="consultation"
        @close="showReviewModal = false"
        @success="fetchDetail"
      />
    </template>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { ArrowLeft, ArrowRight, Check, ChevronRight, Printer } from '@lucide/vue'
import api from '../utils/axios'
import { toast } from '../composables/useToast'
import ReviewModal from '../components/ReviewModal.vue'

const route = useRoute()
const id = route.params.id

const consultation = ref(null)
const loading = ref(true)
const paymentType = ref(null)
const proofFile = ref(null)
const uploading = ref(false)
const showReviewModal = ref(false)

const printDocket = () => {
  window.print()
}

const fetchDetail = async () => {
  try {
    loading.value = true
    const res = await api.get(`/consultations/${id}`)
    consultation.value = res.data.data || res.data
  } catch (err) {
    toast.error('Gagal memuat detail berkas perkara')
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchDetail()
})

const totalTarif = computed(() => Number(consultation.value?.tarif_konsultasi || 0))
const dpAmount = computed(() => Math.floor(totalTarif.value / 2))
const finalAmount = computed(() => totalTarif.value - dpAmount.value)

const progressSteps = computed(() => {
  const s = consultation.value?.status?.toLowerCase() || 'pending'
  const isAccepted = s === 'accepted' || s === 'ongoing' || s === 'waiting_pelunasan' || s === 'completed'
  const isDpPaid = consultation.value?.dp_payment_status === 'paid'
  const isOngoing = s === 'ongoing' || s === 'waiting_pelunasan' || s === 'completed'
  const isWaitingPelunasan = s === 'waiting_pelunasan' || s === 'completed'
  const isDone = s === 'completed'

  return [
    { label: 'Diajukan', active: true, done: isAccepted },
    { label: 'Diterima Advokat', active: isAccepted, done: isDpPaid },
    { label: 'DP Terverifikasi', active: isDpPaid, done: isOngoing },
    { label: 'Konsultasi Rapat', active: isOngoing, done: isWaitingPelunasan },
    { label: 'Pelunasan 50%', active: isWaitingPelunasan, done: isDone },
    { label: 'Perkara Selesai', active: isDone, done: isDone },
  ]
})

const statusBadgeClass = computed(() => {
  const map = {
    pending: 'text-zinc-900 bg-zinc-100 border-zinc-200',
    accepted: 'text-zinc-950 bg-zinc-100 border-zinc-300',
    ongoing: 'text-blue-800 bg-blue-50 border-blue-200',
    waiting_pelunasan: 'text-amber-800 bg-amber-50 border-amber-200',
    completed: 'text-emerald-800 bg-emerald-50 border-emerald-200',
    cancelled: 'text-zinc-400 bg-zinc-100 border-zinc-200',
  }
  const key = consultation.value?.status?.toLowerCase() || 'cancelled'
  return `inline-flex items-center px-3 py-1 rounded-full text-xs font-mono font-semibold uppercase border ${map[key] || map.cancelled}`
})

const copyMeetingLink = () => {
  if (consultation.value?.meeting_link) {
    navigator.clipboard.writeText(consultation.value.meeting_link)
    toast.success('Tautan rapat berhasil disalin ke clipboard')
  }
}

const handleUploadProof = async () => {
  if (!proofFile.value) {
    toast.error('Pilih berkas bukti pembayaran terlebih dahulu')
    return
  }
  uploading.value = true
  const formData = new FormData()
  formData.append('consultation_id', consultation.value.id)

  try {
    if (paymentType.value === 'dp') {
      formData.append('dp_proof', proofFile.value)
      await api.post('/consultations/upload-dp', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      })
    } else {
      formData.append('final_payment_proof', proofFile.value)
      await api.post('/consultations/upload-final-payment', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      })
    }
    toast.success('Bukti pembayaran berhasil diunggah. Menunggu verifikasi tim admin.')
    paymentType.value = null
    proofFile.value = null
    fetchDetail()
  } catch (err) {
    toast.error(err.response?.data?.message || 'Gagal mengirim bukti pembayaran')
  } finally {
    uploading.value = false
  }
}
</script>
