// frontend/counsela/src/pages/Lawyers.vue
<template>
  <div class="space-y-8 text-zinc-950">
    <!-- {Header} -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4 pb-6 border-b border-zinc-200/90">
      <div>
        <div class="text-xs font-semibold text-zinc-500 tracking-wide">
          Direktori Advokat
        </div>
        <h1 class="text-3xl sm:text-4xl font-bold tracking-tight text-zinc-950 mt-1">
          Direktori Advokat
        </h1>
        <p class="text-xs text-zinc-500 mt-1 max-w-xl">
          Temukan advokat sesuai bidang hukum, bandingkan profil, dan jadwalkan konsultasi.
        </p>
      </div>

      <!-- {Search} -->
      <div class="w-full sm:w-80">
        <div class="relative">
          <input
            v-model="searchTerm"
            type="text"
            placeholder="Cari firma, advokat, spesialisasi..."
            class="w-full text-xs px-4 py-2.5 pl-9 rounded-full border border-zinc-200 bg-white text-zinc-900 placeholder-zinc-400 focus:outline-none focus:border-black shadow-2xs"
          />
          <svg class="w-3.5 h-3.5 absolute left-3.5 top-3 text-zinc-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
          </svg>
          <button
            v-if="searchTerm"
            @click="searchTerm = ''"
            class="absolute right-3.5 top-2.5 text-zinc-400 hover:text-zinc-700 flex items-center justify-center p-0.5 cursor-pointer"
          >
            <X class="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </div>

    <!-- {Filter Bar} -->
    <div class="bg-white border border-zinc-200/90 rounded-2xl p-4 shadow-2xs space-y-4">
      <!-- {Categories} -->
      <div class="flex items-center justify-between gap-3 overflow-x-auto pb-1">
        <div class="flex flex-wrap items-center gap-1.5 min-w-max">
          <button
            v-for="cat in categories"
            :key="cat"
            @click="selectedCategory = cat"
            class="px-3 py-1.5 rounded-full text-xs font-medium transition-all cursor-pointer"
            :class="selectedCategory === cat
              ? 'bg-black text-white font-semibold shadow-2xs'
              : 'bg-zinc-100/80 text-zinc-700 hover:bg-zinc-200/70'"
          >
            {{ cat }}
          </button>
        </div>

        <!-- {View Mode} -->
        <div class="flex items-center gap-1 bg-zinc-100 p-1 rounded-full border border-zinc-200 shrink-0">
          <button
            @click="viewMode = 'grid'"
            class="px-3 py-1 text-xs font-medium rounded-full transition-colors flex items-center gap-1.5 cursor-pointer"
            :class="viewMode === 'grid' ? 'bg-white text-black shadow-2xs' : 'text-zinc-500 hover:text-black'"
            title="Tampilan Grid"
          >
            <LayoutGrid class="w-3.5 h-3.5" />
            <span class="hidden sm:inline">Grid</span>
          </button>
          <button
            @click="viewMode = 'table'"
            class="px-3 py-1 text-xs font-medium rounded-full transition-colors flex items-center gap-1.5 cursor-pointer"
            :class="viewMode === 'table' ? 'bg-white text-black shadow-2xs' : 'text-zinc-500 hover:text-black'"
            title="Tampilan Tabel"
          >
            <List class="w-3.5 h-3.5" />
            <span class="hidden sm:inline">Tabel</span>
          </button>
        </div>
      </div>

      <!-- {Controls} -->
      <div class="flex flex-wrap items-center justify-between gap-4 pt-3 border-t border-zinc-100 text-xs">
        <div class="flex flex-wrap items-center gap-4">
          <!-- {Availability} -->
          <label class="flex items-center gap-2 cursor-pointer select-none text-zinc-700 font-medium">
            <input
              type="checkbox"
              v-model="onlyAvailable"
              class="w-3.5 h-3.5 rounded text-black accent-black cursor-pointer"
            />
            <span>Hanya yang siap menerima konsultasi</span>
          </label>

          <!-- {Experience} -->
          <div class="flex items-center gap-1.5 text-zinc-600">
            <span class="text-xs text-zinc-500 font-medium">Pengalaman:</span>
            <select
              v-model.number="minExperience"
              class="p-1 px-2 rounded-lg border border-zinc-200 bg-zinc-50 text-xs font-medium cursor-pointer"
            >
              <option :value="0">Semua</option>
              <option :value="5">&gt; 5 Tahun</option>
              <option :value="10">&gt; 10 Tahun</option>
              <option :value="15">&gt; 15 Tahun</option>
            </select>
          </div>
        </div>

        <!-- {Sort} -->
        <div class="flex items-center gap-2">
          <span class="text-xs text-zinc-500 font-medium">Urutkan:</span>
          <select
            v-model="sortBy"
            class="text-xs font-medium px-3 py-1.5 rounded-full border border-zinc-200 bg-white text-zinc-800 focus:outline-none focus:border-black cursor-pointer"
          >
            <option value="rating">Rating Tertinggi</option>
            <option value="pengalaman">Pengalaman Terlama</option>
            <option value="tarif_asc">Tarif Terendah</option>
            <option value="tarif_desc">Tarif Tertinggi</option>
          </select>
        </div>
      </div>
    </div>

    <!-- {Counter} -->
    <div class="flex flex-wrap items-center justify-between text-xs text-zinc-500">
      <div class="flex items-center gap-2">
        <span>Menampilkan <strong class="text-zinc-900 font-semibold">{{ filteredAndSortedLawyers.length }}</strong> dari <strong class="text-zinc-900 font-semibold">{{ lawyers.length }}</strong> advokat</span>
        <button v-if="selectedCategory !== 'Semua Bidang' || searchTerm || onlyAvailable || minExperience > 0" class="text-black font-semibold hover:underline ml-2 cursor-pointer" @click="resetFilters">
          Reset Filter
        </button>
      </div>
      <span class="text-zinc-400 hidden sm:inline">Pilih centang bandingkan untuk komparasi profil</span>
    </div>

    <!-- {Loading} -->
    <div v-if="loading" class="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-3 gap-2.5 sm:gap-6">
      <div
        v-for="i in 6"
        :key="i"
        class="h-56 sm:h-64 bg-zinc-100 rounded-2xl sm:rounded-3xl animate-pulse border border-zinc-200"
      ></div>
    </div>

    <!-- {Empty} -->
    <div
      v-else-if="paginatedLawyers.length === 0"
      class="p-16 text-center bg-white border border-zinc-200 rounded-3xl text-xs text-zinc-500 space-y-3"
    >
      <p class="text-base font-bold text-zinc-900">Tidak ada advokat yang memenuhi kriteria</p>
      <p class="max-w-md mx-auto">
        Kombinasi filter yang Anda pilih saat ini belum memiliki kecocokan data.
      </p>
      <button
        @click="resetFilters"
        class="px-5 py-2 text-xs font-semibold bg-black text-white rounded-full hover:bg-zinc-800 transition-colors cursor-pointer"
      >
        Tampilkan Semua Advokat
      </button>
    </div>

    <!-- {Grid View} -->
    <div v-else-if="viewMode === 'grid'" class="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-3 gap-2.5 sm:gap-6">
      <LawyerCard
        v-for="lawyer in paginatedLawyers"
        :key="lawyer.id"
        :lawyer="lawyer"
        :is-compared="isCompared(lawyer.id)"
        @toggle-compare="handleToggleCompare"
      />
    </div>

    <!-- {Table View} -->
    <div v-else-if="viewMode === 'table'" class="bg-white border border-zinc-200/90 rounded-2xl overflow-hidden shadow-2xs">
      <div class="overflow-x-auto">
        <table class="w-full text-xs text-left border-collapse">
          <thead>
            <tr class="bg-zinc-50 border-b border-zinc-200 text-xs font-medium text-zinc-500">
              <th class="py-3 px-4 w-12 text-center">Pilih</th>
              <th class="py-3 px-4">Advokat & Firma</th>
              <th class="py-3 px-4">Spesialisasi</th>
              <th class="py-3 px-4">Pengalaman</th>
              <th class="py-3 px-4">Rating</th>
              <th class="py-3 px-4">Tarif Sesi</th>
              <th class="py-3 px-4">Status</th>
              <th class="py-3 px-4 text-right">Aksi</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-zinc-100">
            <tr
              v-for="l in paginatedLawyers"
              :key="l.id"
              class="hover:bg-zinc-50/70 transition-colors"
            >
              <!-- {Checkbox} -->
              <td class="py-3 px-4 text-center">
                <input
                  type="checkbox"
                  :checked="isCompared(l.id)"
                  @change="handleToggleCompare(l)"
                  class="w-3.5 h-3.5 rounded accent-black cursor-pointer"
                />
              </td>

              <!-- {Lawyer} -->
              <td class="py-3 px-4">
                <div class="flex items-center gap-3">
                  <img
                    :src="l.foto_profil || defaultAvatar"
                    :alt="l.firma_hukum"
                    class="w-9 h-9 rounded-xl object-cover border border-zinc-200 bg-zinc-100 shrink-0"
                  />
                  <div>
                    <RouterLink :to="`/lawyers/${l.id}`" class="font-bold text-zinc-950 hover:underline block leading-snug">
                      {{ l.firma_hukum }}
                    </RouterLink>
                    <span class="text-[11px] font-mono text-zinc-400 block">#ADV-{{ String(l.id).padStart(3, '0') }}</span>
                  </div>
                </div>
              </td>

              <!-- {Specialty} -->
              <td class="py-3 px-4 font-medium text-zinc-800">
                {{ l.spesialisasi }}
              </td>

              <!-- {Experience} -->
              <td class="py-3 px-4 text-zinc-600">
                {{ l.pengalaman || 0 }} Tahun
              </td>

              <!-- {Rating} -->
              <td class="py-3 px-4">
                <span class="inline-flex items-center gap-1 font-mono font-semibold text-zinc-900 bg-zinc-100 px-2 py-0.5 rounded-full border border-zinc-200 text-[11px]">
                  <Star class="w-3 h-3 fill-zinc-900 text-zinc-900" />
                  <span>{{ Number(l.rating || 5).toFixed(1) }}</span>
                </span>
              </td>

              <!-- {Fee} -->
              <td class="py-3 px-4">
                <span class="font-bold text-zinc-950 block">
                  Rp {{ Number(l.tarif_konsultasi || 0).toLocaleString('id-ID') }}
                </span>
                <span class="text-[11px] text-zinc-400">
                  DP 50%: Rp {{ Math.floor(Number(l.tarif_konsultasi || 0) / 2).toLocaleString('id-ID') }}
                </span>
              </td>

              <!-- {Status} -->
              <td class="py-3 px-4">
                <span
                  class="inline-flex items-center gap-1 text-[11px] font-medium px-2 py-0.5 rounded-full"
                  :class="l.status_aktif ? 'bg-emerald-50 text-emerald-800 border border-emerald-200' : 'bg-zinc-100 text-zinc-400 border border-zinc-200'"
                >
                  <span class="w-1.5 h-1.5 rounded-full" :class="l.status_aktif ? 'bg-emerald-500' : 'bg-zinc-400'"></span>
                  {{ l.status_aktif ? 'Aktif' : 'Penuh' }}
                </span>
              </td>

              <!-- {Action} -->
              <td class="py-3 px-4 text-right">
                <div class="flex items-center justify-end gap-1.5">
                  <RouterLink
                    :to="`/lawyers/${l.id}`"
                    class="px-2.5 py-1 text-xs font-medium border border-zinc-200 hover:bg-zinc-100 text-zinc-700 rounded-full transition-colors"
                  >
                    Lihat Profil
                  </RouterLink>
                  <RouterLink
                    :to="`/consultation/new?lawyer=${l.id}`"
                    class="inline-flex items-center gap-1 px-3 py-1 text-xs font-medium bg-black hover:bg-zinc-800 text-white rounded-full transition-colors shadow-2xs"
                  >
                    <span>Pilih Advokat</span>
                    <ArrowRight class="w-3 h-3" />
                  </RouterLink>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- {Pagination} -->
    <div v-if="totalPages > 1" class="flex justify-center items-center gap-2 pt-6 border-t border-zinc-200">
      <button
        :disabled="currentPage === 1"
        @click="currentPage--"
        class="px-3.5 py-1.5 rounded-full text-xs font-medium border border-zinc-200 text-zinc-700 hover:bg-zinc-50 disabled:opacity-30 disabled:cursor-not-allowed cursor-pointer"
      >
        Sebelumnya
      </button>

      <div class="flex items-center gap-1">
        <button
          v-for="page in totalPages"
          :key="page"
          @click="currentPage = page"
          class="w-8 h-8 rounded-full text-xs font-mono font-semibold transition-all cursor-pointer"
          :class="currentPage === page
            ? 'bg-black text-white shadow-2xs'
            : 'bg-white border border-zinc-200 text-zinc-700 hover:bg-zinc-50'"
        >
          {{ page }}
        </button>
      </div>

      <button
        :disabled="currentPage === totalPages"
        @click="currentPage++"
        class="px-3.5 py-1.5 rounded-full text-xs font-medium border border-zinc-200 text-zinc-700 hover:bg-zinc-50 disabled:opacity-30 disabled:cursor-not-allowed cursor-pointer"
      >
        Selanjutnya
      </button>
    </div>

    <!-- {Compare Drawer} -->
    <LawyerCompareDrawer
      :selected-lawyers="comparedLawyers"
      @clear="comparedLawyers = []"
    />
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { LayoutGrid, List, Star, X, ArrowRight } from '@lucide/vue'
import lawyerService from '../service/lawyerService'
import LawyerCard from '../components/LawyerCard.vue'
import LawyerCompareDrawer from '../components/LawyerCompareDrawer.vue'

const route = useRoute()

const lawyers = ref([])
const loading = ref(true)
const searchTerm = ref('')
const selectedCategory = ref('Semua Bidang')
const sortBy = ref('rating')
const viewMode = ref('grid')
const onlyAvailable = ref(false)
const minExperience = ref(0)
const currentPage = ref(1)
const itemsPerPage = 9
const comparedLawyers = ref([])

const defaultAvatar =
  'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=400&q=80'

const categories = [
  'Semua Bidang',
  'Bisnis & Korporasi',
  'Pidana',
  'Perdata',
  'Ketenagakerjaan',
  'Kekayaan Intelektual',
  'Properti',
]

const isCompared = (id) => comparedLawyers.value.some((l) => l.id === id)

const handleToggleCompare = (lawyer) => {
  const idx = comparedLawyers.value.findIndex((l) => l.id === lawyer.id)
  if (idx > -1) {
    comparedLawyers.value.splice(idx, 1)
  } else {
    if (comparedLawyers.value.length >= 3) {
      alert('Maksimal komparasi 3 advokat sekaligus.')
      return
    }
    comparedLawyers.value.push(lawyer)
  }
}

const resetFilters = () => {
  searchTerm.value = ''
  selectedCategory.value = 'Semua Bidang'
  sortBy.value = 'rating'
  onlyAvailable.value = false
  minExperience.value = 0
  currentPage.value = 1
}

onMounted(async () => {
  if (route.query.domain) {
    const d = route.query.domain
    if (d.includes('Bisnis') || d.includes('Korporasi')) selectedCategory.value = 'Bisnis & Korporasi'
    else if (d.includes('Pidana')) selectedCategory.value = 'Pidana'
    else if (d.includes('Ketenagakerjaan')) selectedCategory.value = 'Ketenagakerjaan'
    else if (d.includes('Properti') || d.includes('Lahan')) selectedCategory.value = 'Properti'
    else if (d.includes('Intelektual') || d.includes('HKI')) selectedCategory.value = 'Kekayaan Intelektual'
    else searchTerm.value = d
  }

  try {
    loading.value = true
    const res = await lawyerService.getAllLawyers()
    lawyers.value = Array.isArray(res) ? res : []
  } catch (err) {
    console.error('Failed to load lawyers:', err)
  } finally {
    loading.value = false
  }
})

watch([searchTerm, selectedCategory, sortBy, onlyAvailable, minExperience], () => {
  currentPage.value = 1
})

const filteredAndSortedLawyers = computed(() => {
  let list = [...lawyers.value]

  if (selectedCategory.value !== 'Semua Bidang') {
    const cat = selectedCategory.value.toLowerCase()
    list = list.filter((l) => l.spesialisasi?.toLowerCase().includes(cat))
  }

  if (searchTerm.value.trim()) {
    const q = searchTerm.value.toLowerCase().trim()
    list = list.filter(
      (l) =>
        l.firma_hukum?.toLowerCase().includes(q) ||
        l.spesialisasi?.toLowerCase().includes(q) ||
        l.deskripsi?.toLowerCase().includes(q) ||
        l.nama?.toLowerCase().includes(q)
    )
  }

  if (onlyAvailable.value) {
    list = list.filter((l) => l.status_aktif)
  }

  if (minExperience.value > 0) {
    list = list.filter((l) => Number(l.pengalaman || 0) >= minExperience.value)
  }

  if (sortBy.value === 'rating') {
    list.sort((a, b) => Number(b.rating || 0) - Number(a.rating || 0))
  } else if (sortBy.value === 'pengalaman') {
    list.sort((a, b) => Number(b.pengalaman || 0) - Number(a.pengalaman || 0))
  } else if (sortBy.value === 'tarif_asc') {
    list.sort((a, b) => Number(a.tarif_konsultasi || 0) - Number(b.tarif_konsultasi || 0))
  } else if (sortBy.value === 'tarif_desc') {
    list.sort((a, b) => Number(b.tarif_konsultasi || 0) - Number(a.tarif_konsultasi || 0))
  }

  return list
})

const totalPages = computed(() => {
  return Math.ceil(filteredAndSortedLawyers.value.length / itemsPerPage)
})

const paginatedLawyers = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage
  return filteredAndSortedLawyers.value.slice(start, start + itemsPerPage)
})
</script>

// frontend/counsela/src/pages/Lawyers.jsx
import { useEffect, useState } from "react"
import { Link } from "react-router-dom"
import { motion } from "framer-motion"
import LawyerCard from "../components/LawyerCard"
import useLawyers from "../hooks/useLawyers"

const Icons = {
  ArrowLeft: () => (
    <svg className="w-4 h-4 group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 18l-6-6 6-6" />
    </svg>
  ),
  Search: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
  ),
  ChevronLeft: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
    </svg>
  ),
  ChevronRight: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
    </svg>
  ),
}

const Lawyers = () => {
  const { lawyers, loading, fetchLawyers } = useLawyers()
  const [searchTerm, setSearchTerm] = useState("")
  const [currentPage, setCurrentPage] = useState(1)
  const itemsPerPage = 6

  useEffect(() => {
    fetchLawyers()
  }, [])

  // Filter lawyers berdasarkan search
  const filteredLawyers = lawyers.filter(lawyer =>
    lawyer.firma_hukum?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    lawyer.spesialisasi?.toLowerCase().includes(searchTerm.toLowerCase())
  )

  // Pagination logic
  const totalPages = Math.ceil(filteredLawyers.length / itemsPerPage)
  const startIndex = (currentPage - 1) * itemsPerPage
  const endIndex = startIndex + itemsPerPage
  const currentLawyers = filteredLawyers.slice(startIndex, endIndex)

  // Reset ke halaman 1 saat search berubah
  useEffect(() => {
    setCurrentPage(1)
  }, [searchTerm])

  const goToPage = (page) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page)
      // TIDAK ADA window.scrollTo - ScrollToTop sudah handle scroll otomatis
    }
  }

  const goToPrevPage = () => goToPage(currentPage - 1)
  const goToNextPage = () => goToPage(currentPage + 1)

  // Generate page numbers untuk ditampilkan
  const getPageNumbers = () => {
    const pages = []
    const maxVisible = 5
    let startPage = Math.max(1, currentPage - Math.floor(maxVisible / 2))
    let endPage = Math.min(totalPages, startPage + maxVisible - 1)
    
    if (endPage - startPage + 1 < maxVisible) {
      startPage = Math.max(1, endPage - maxVisible + 1)
    }
    
    for (let i = startPage; i <= endPage; i++) {
      pages.push(i)
    }
    return pages
  }

  return (
    <div>
      {/* Hero Section */}
      <div className="relative mb-8 overflow-hidden rounded-2xl md:rounded-3xl bg-gradient-to-r from-blue-700 via-indigo-800 to-purple-900 text-white">
        <div className="absolute inset-0 bg-black/20" />
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-0 w-80 h-80 bg-white/10 rounded-full blur-3xl" />
        
        <div className="relative z-10 px-6 py-12 md:py-16 text-center">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-white/80 hover:text-white mb-4 transition-all duration-200 group"
          >
            <Icons.ArrowLeft />
            Kembali ke Beranda
          </Link>
          <h1 className="text-3xl md:text-5xl font-bold">Temukan Lawyer Terbaik</h1>
          <p className="mt-3 text-blue-100 max-w-2xl mx-auto">
            Hubungi pengacara profesional dan terpercaya untuk membantu kebutuhan hukum Anda
          </p>
          
          {/* Search Bar */}
          <div className="max-w-md mx-auto mt-8">
            <div className="relative">
              <input
                type="text"
                placeholder="Cari lawyer berdasarkan nama firma atau spesialisasi..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full px-5 py-3 pl-12 rounded-full bg-white/10 backdrop-blur-sm border border-white/20 text-white placeholder-white/60 focus:outline-none focus:ring-2 focus:ring-white/30 transition"
              />
              <div className="absolute left-4 top-1/2 -translate-y-1/2">
                <Icons.Search />
              </div>
            </div>
          </div>
        </div>
        
        <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-gray-50 dark:from-gray-950 to-transparent" />
      </div>

      {/* Result Info */}
      {!loading && filteredLawyers.length > 0 && (
        <div className="mb-4 text-gray-500 dark:text-gray-400 text-sm">
          Menampilkan {startIndex + 1}-{Math.min(endIndex, filteredLawyers.length)} dari {filteredLawyers.length} lawyer
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1,2,3,4,5,6].map(i => (
            <div key={i} className="h-96 bg-gray-200 dark:bg-gray-800 rounded-2xl animate-pulse" />
          ))}
        </div>
      )}

      {/* Empty */}
      {!loading && filteredLawyers.length === 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center py-16 bg-white dark:bg-gray-800 rounded-2xl shadow"
        >
          <div className="w-20 h-20 mx-auto bg-gray-100 dark:bg-gray-700 rounded-full flex items-center justify-center mb-4">
            <Icons.Search />
          </div>
          <h2 className="text-xl font-bold text-gray-700 dark:text-gray-300">Tidak Ada Lawyer Ditemukan</h2>
          <p className="text-gray-500 dark:text-gray-400 mt-2">
            {searchTerm ? `Tidak ada lawyer dengan kata "${searchTerm}"` : "Belum ada lawyer terdaftar"}
          </p>
          {searchTerm && (
            <button
              onClick={() => setSearchTerm("")}
              className="mt-4 text-blue-600 hover:underline"
            >
              Hapus pencarian
            </button>
          )}
        </motion.div>
      )}

      {/* List Lawyer */}
      {!loading && filteredLawyers.length > 0 && (
        <>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {currentLawyers.map((lawyer, idx) => (
              <motion.div
                key={lawyer.id}
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: (idx % 6) * 0.05 }}
              >
                <LawyerCard lawyer={lawyer} />
              </motion.div>
            ))}
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex justify-center items-center gap-2 mt-10">
              <button
                onClick={goToPrevPage}
                disabled={currentPage === 1}
                className={`p-2 rounded-xl transition-all duration-200 ${
                  currentPage === 1
                    ? "text-gray-400 cursor-not-allowed"
                    : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                }`}
              >
                <Icons.ChevronLeft />
              </button>
              
              {getPageNumbers().map(page => (
                <button
                  key={page}
                  onClick={() => goToPage(page)}
                  className={`w-10 h-10 rounded-xl font-medium transition-all duration-200 ${
                    currentPage === page
                      ? "bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-md"
                      : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                  }`}
                >
                  {page}
                </button>
              ))}
              
              <button
                onClick={goToNextPage}
                disabled={currentPage === totalPages}
                className={`p-2 rounded-xl transition-all duration-200 ${
                  currentPage === totalPages
                    ? "text-gray-400 cursor-not-allowed"
                    : "text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
                }`}
              >
                <Icons.ChevronRight />
              </button>
            </div>
          )}
        </>
      )}
    </div>
  )
}

export default Lawyers
