// frontend/counsela/src/pages/LawyerDashboard.vue
<template>
  <div class="space-y-8 text-zinc-950">
    <!-- {Header} -->
    <div class="pb-6 border-b border-zinc-200">
      <div class="text-xs font-semibold text-zinc-500 tracking-wide">
        Portal Advokat
      </div>
      <h1 class="text-3xl font-bold tracking-tight text-zinc-950 mt-1">
        Dashboard Advokat
      </h1>
      <p class="text-xs text-zinc-500 mt-1">
        Kelola jadwal konsultasi, terima permintaan klien, dan atur tautan rapat.
      </p>
    </div>

    <!-- {Stats} -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <div
        v-for="(item, idx) in stats"
        :key="idx"
        class="p-5 bg-white border border-zinc-200/90 rounded-2xl shadow-2xs space-y-1.5 hover:border-zinc-300 transition-colors"
      >
        <span class="text-xs font-medium text-zinc-500 block">
          {{ item.label }}
        </span>
        <span class="text-3xl font-bold tracking-tight block" :class="item.color">
          {{ item.count }}
        </span>
      </div>
    </div>

    <!-- {Orders Table} -->
    <div class="bg-white border border-zinc-200/90 rounded-3xl shadow-sm overflow-hidden">
      <div class="px-6 py-5 border-b border-zinc-200 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
        <div>
          <h2 class="text-base font-bold text-zinc-950 tracking-tight">
            Permintaan Konsultasi
          </h2>
          <p class="text-xs text-zinc-500">Daftar konsultasi yang masuk ke jadwal Anda</p>
        </div>
        <span class="text-xs font-medium text-zinc-600 bg-zinc-100 px-3 py-1 rounded-full border border-zinc-200">
          Total <strong class="text-zinc-900 font-semibold">{{ myOrders.length }}</strong> Kasus
        </span>
      </div>

      <div v-if="loading" class="p-12 text-center text-xs text-zinc-400 font-sans">
        Memuat daftar konsultasi...
      </div>

      <div
        v-else-if="myOrders.length === 0"
        class="p-16 text-center text-xs text-zinc-500 space-y-2"
      >
        <p class="text-base font-bold text-zinc-800">Belum ada permintaan konsultasi</p>
        <p>Permintaan konsultasi baru dari klien akan muncul di sini.</p>
      </div>

      <div v-else class="overflow-x-auto">
        <table class="w-full text-left text-xs sm:text-sm">
          <thead class="bg-zinc-50 text-zinc-500 text-xs font-medium border-b border-zinc-200">
            <tr>
              <th class="px-6 py-3.5">Klien</th>
              <th class="px-6 py-3.5">Pokok Kasus</th>
              <th class="px-6 py-3.5">Jadwal Sesi</th>
              <th class="px-6 py-3.5">Status</th>
              <th class="px-6 py-3.5 text-right">Aksi</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-zinc-100 text-zinc-700">
            <tr
              v-for="c in myOrders"
              :key="c.id"
              class="hover:bg-zinc-50/70 transition-colors"
            >
              <td class="px-6 py-4 font-bold text-zinc-950">
                {{ c.client_name || '-' }}
              </td>
              <td class="px-6 py-4 max-w-xs truncate font-medium text-zinc-900">
                {{ c.judul_kasus }}
              </td>
              <td class="px-6 py-4 text-xs font-mono whitespace-nowrap">
                {{ c.tanggal_konsultasi?.split('T')[0] }} • {{ c.jam_konsultasi }} WIB
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span :class="getStatusBadge(c.status)">
                  {{ c.status?.replace('_', ' ') }}
                </span>
              </td>
              <td class="px-6 py-4 text-right space-x-2 whitespace-nowrap">
                <!-- {Actions Pending} -->
                <template v-if="c.status === 'pending'">
                  <button
                    @click="handleAction(c.id, 'accept')"
                    :disabled="loadingAction"
                    class="inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold bg-black hover:bg-zinc-800 text-white rounded-full transition-colors shadow-2xs disabled:opacity-50"
                  >
                    <Check class="w-3 h-3" />
                    <span>Terima</span>
                  </button>
                  <button
                    @click="handleAction(c.id, 'reject')"
                    :disabled="loadingAction"
                    class="inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold border border-zinc-300 hover:bg-zinc-100 text-zinc-800 rounded-full transition-colors disabled:opacity-50"
                  >
                    <X class="w-3 h-3" />
                    <span>Tolak</span>
                  </button>
                </template>

                <!-- {Actions Meeting Link} -->
                <button
                  v-if="c.status === 'accepted' && c.dp_payment_status === 'paid'"
                  @click="openMeetingModal(c)"
                  class="inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold bg-emerald-700 hover:bg-emerald-800 text-white rounded-full transition-colors shadow-2xs"
                >
                  <Video class="w-3 h-3" />
                  <span>Tautan Rapat</span>
                </button>

                <!-- {Actions Complete} -->
                <button
                  v-if="c.status === 'ongoing'"
                  @click="handleAction(c.id, 'complete')"
                  :disabled="loadingAction"
                  class="inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold bg-zinc-900 hover:bg-black text-white rounded-full transition-colors shadow-2xs disabled:opacity-50"
                >
                  <CheckCircle class="w-3 h-3" />
                  <span>Selesaikan</span>
                </button>

                <RouterLink
                  :to="`/consultations/${c.id}`"
                  class="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-zinc-600 hover:text-zinc-950 hover:underline"
                >
                  <FileText class="w-3 h-3" />
                  <span>Detail</span>
                </RouterLink>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- {Meeting Modal} -->
    <div
      v-if="meetingModal"
      class="fixed inset-0 bg-black/40 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-in fade-in duration-150"
    >
      <form
        @submit.prevent="handleSaveMeeting"
        class="bg-white border border-zinc-200 rounded-3xl p-6 w-full max-w-md space-y-4 shadow-2xl text-sm"
      >
        <div class="flex items-start justify-between">
          <div>
            <div class="font-mono text-[10px] text-zinc-400 uppercase tracking-wider font-semibold">
              Tautan Rapat
            </div>
            <h3 class="font-bold text-lg text-zinc-950 mt-1 tracking-tight">
              Tautan Rapat Konsultasi
            </h3>
            <p class="text-xs text-zinc-500 mt-1">
              Masukkan URL Google Meet atau Zoom untuk sesi klien: <strong>{{ meetingModal.client_name }}</strong>
            </p>
          </div>
          <button
            type="button"
            @click="meetingModal = null"
            class="w-7 h-7 rounded-full border border-zinc-200 hover:bg-zinc-100 text-zinc-600 flex items-center justify-center transition-colors"
          >
            <X class="w-3.5 h-3.5" />
          </button>
        </div>

        <div>
          <label class="block text-xs font-semibold text-zinc-700 mb-1.5">
            URL Rapat
          </label>
          <input
            v-model="meetingLink"
            type="url"
            placeholder="https://meet.google.com/xyz-abcd-efg"
            class="w-full text-xs sm:text-sm px-3.5 py-2.5 rounded-2xl border border-zinc-200 bg-white text-zinc-900 focus:outline-none focus:border-zinc-900 shadow-2xs font-mono"
            required
          />
        </div>

        <div class="flex justify-end gap-2 pt-3 border-t border-zinc-100">
          <button
            type="button"
            @click="meetingModal = null"
            class="px-4 py-2 text-xs font-semibold text-zinc-600 hover:text-black transition-colors"
          >
            Batal
          </button>
          <button
            type="submit"
            :disabled="loadingAction"
            class="px-5 py-2 text-xs font-semibold bg-black hover:bg-zinc-800 text-white rounded-full transition-all disabled:opacity-50 shadow-sm"
          >
            {{ loadingAction ? 'Menyimpan...' : 'Simpan & Beritahu Klien' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { Check, X, Video, CheckCircle, FileText } from '@lucide/vue'
import { useAuth } from '../composables/useAuth'
import api from '../utils/axios'
import { toast } from '../composables/useToast'

const { user } = useAuth()

const consultations = ref([])
const loading = ref(true)
const meetingModal = ref(null)
const meetingLink = ref('')
const loadingAction = ref(false)

const fetchConsultations = async () => {
  try {
    loading.value = true
    const res = await api.get('/consultations')
    consultations.value = res.data.data || res.data || []
  } catch (err) {
    toast.error('Gagal memuat konsultasi perkara')
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchConsultations()
})

const myOrders = computed(() => {
  return consultations.value.filter(
    (c) => c.lawyer_id === user.value?.id || c.lawyer_name === user.value?.nama
  )
})

const stats = computed(() => [
  {
    label: 'Permintaan Baru',
    count: myOrders.value.filter((c) => c.status === 'pending').length,
    color: 'text-amber-700',
  },
  {
    label: 'Siap Sesi (DP Lunas)',
    count: myOrders.value.filter((c) => c.status === 'accepted' && c.dp_payment_status === 'paid').length,
    color: 'text-blue-700',
  },
  {
    label: 'Konsultasi Berjalan',
    count: myOrders.value.filter((c) => c.status === 'ongoing').length,
    color: 'text-indigo-700',
  },
  {
    label: 'Perkara Selesai',
    count: myOrders.value.filter((c) => c.status === 'completed').length,
    color: 'text-emerald-700',
  },
])

const handleAction = async (id, actionType) => {
  loadingAction.value = true
  try {
    if (actionType === 'accept') {
      await api.patch(`/consultations/${id}/accept`)
    } else if (actionType === 'reject') {
      await api.patch(`/consultations/${id}/status`, { status: 'cancelled' })
    } else if (actionType === 'complete') {
      await api.patch(`/consultations/${id}/complete-case`)
    }
    toast.success('Status perkara berhasil diperbarui')
    await fetchConsultations()
  } catch (err) {
    toast.error('Gagal memproses perubahan status perkara')
  } finally {
    loadingAction.value = false
  }
}

const openMeetingModal = (c) => {
  meetingModal.value = c
  meetingLink.value = c.meeting_link || ''
}

const handleSaveMeeting = async () => {
  if (!meetingLink.value.trim()) {
    toast.error('Masukkan URL video conference rapat')
    return
  }
  loadingAction.value = true
  try {
    await api.patch(`/consultations/${meetingModal.value.id}/add-meeting-link`, {
      meeting_link: meetingLink.value,
    })
    toast.success('Tautan rapat berhasil disimpan')
    meetingModal.value = null
    meetingLink.value = ''
    await fetchConsultations()
  } catch {
    toast.error('Gagal menyimpan tautan rapat')
  } finally {
    loadingAction.value = false
  }
}

const getStatusBadge = (status) => {
  const map = {
    pending: 'text-amber-800 bg-amber-50 border-amber-200',
    accepted: 'text-blue-800 bg-blue-50 border-blue-200',
    ongoing: 'text-indigo-800 bg-indigo-50 border-indigo-200',
    waiting_pelunasan: 'text-orange-800 bg-orange-50 border-orange-200',
    completed: 'text-emerald-800 bg-emerald-50 border-emerald-200',
    cancelled: 'text-slate-600 bg-slate-100 border-slate-200',
  }
  return `inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-medium border ${map[status?.toLowerCase()] || map.cancelled}`
}
</script>

// frontend/counsela/src/pages/LawyerDashboard.jsx
import { useEffect, useState } from "react"
import useAuth from "../hooks/useAuth"
import useConsultations from "../hooks/useConsultations"
import api from "../utils/axios"
import { toast } from "react-hot-toast"
import { motion, AnimatePresence } from "framer-motion"

const Icons = {
  Calendar: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
  ),
  Clock: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Money: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Chat: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
    </svg>
  ),
  CheckCircle: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Loading: () => (
    <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
    </svg>
  ),
  ExternalLink: () => (
    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
    </svg>
  ),
  Trash: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
    </svg>
  ),
  AlertTriangle: () => (
    <svg className="w-12 h-12 mx-auto text-yellow-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
    </svg>
  ),
}

const LawyerDashboard = () => {
  const { user } = useAuth()
  const { consultations, fetchConsultations } = useConsultations()
  const [showMeetingModal, setShowMeetingModal] = useState(null)
  const [meetingLink, setMeetingLink] = useState("")
  const [loadingAction, setLoadingAction] = useState(false)
  const [confirmData, setConfirmData] = useState({ isOpen: false, id: null, action: null, title: "", message: "" })

  const myConsultations = consultations.filter(c => 
    c.lawyer_id === user?.id || c.lawyer_name === user?.nama
  )
  
  const pendingOrders = myConsultations.filter(c => c.status === "pending")
  const acceptedOrders = myConsultations.filter(c => c.status === "accepted" && c.dp_payment_status !== "paid")
  const dpPaidOrders = myConsultations.filter(c => c.status === "accepted" && c.dp_payment_status === "paid")
  const ongoingOrders = myConsultations.filter(c => c.status === "ongoing")
  const waitingPelunasanOrders = myConsultations.filter(c => c.status === "waiting_pelunasan")
  const completedOrders = myConsultations.filter(c => c.status === "completed")

  useEffect(() => { 
    fetchConsultations() 
  }, [])

  const showConfirm = (id, action, title, message) => {
    setConfirmData({ isOpen: true, id, action, title, message })
  }

  const handleConfirm = async () => {
    const { id, action } = confirmData
    setLoadingAction(true)
    try {
      if (action === 'accept') {
        await api.patch(`/consultations/${id}/accept`)
        toast.success("Orderan diterima!")
      } else if (action === 'reject') {
        await api.patch(`/consultations/${id}/status`, { status: "cancelled" })
        toast.success("Orderan ditolak")
      } else if (action === 'complete') {
        await api.patch(`/consultations/${id}/complete-case`)
        toast.success("Kasus selesai! Client dapat melakukan pelunasan.")
      } else if (action === 'hide') {
        await api.patch(`/consultations/${id}/hide`)
        toast.success("Riwayat dihapus dari tampilan Anda")
      }
      await fetchConsultations()
    } catch (err) {
      toast.error("Gagal melakukan aksi")
    } finally {
      setLoadingAction(false)
      setConfirmData({ isOpen: false, id: null, action: null, title: "", message: "" })
    }
  }

  const handleAddMeetingLink = async (id) => {
    if (!meetingLink.trim()) {
      toast.error("Meeting link wajib diisi")
      return
    }
    setLoadingAction(true)
    try {
      await api.patch(`/consultations/${id}/add-meeting-link`, { meeting_link: meetingLink })
      toast.success("Meeting link berhasil ditambahkan! Konsultasi bisa dimulai.")
      await fetchConsultations()
      setShowMeetingModal(null)
      setMeetingLink("")
    } catch (err) {
      toast.error(err.response?.data?.message || "Gagal menambahkan meeting link")
    } finally {
      setLoadingAction(false)
    }
  }

  const getStatusBadge = (consultation) => {
    if (consultation.status === "pending") {
      return <span className="px-2 py-1 rounded-full text-xs bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400">Menunggu Diterima</span>
    }
    if (consultation.status === "accepted" && consultation.dp_payment_status !== "paid") {
      return <span className="px-2 py-1 rounded-full text-xs bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">Menunggu DP</span>
    }
    if (consultation.dp_payment_status === "waiting_verification") {
      return <span className="px-2 py-1 rounded-full text-xs bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400">Verifikasi DP</span>
    }
    if (consultation.status === "accepted" && consultation.dp_payment_status === "paid") {
      return <span className="px-2 py-1 rounded-full text-xs bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400">DP Lunas, Siap Meeting</span>
    }
    if (consultation.status === "ongoing") {
      return <span className="px-2 py-1 rounded-full text-xs bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400">Konsultasi Berjalan</span>
    }
    if (consultation.status === "waiting_pelunasan") {
      return <span className="px-2 py-1 rounded-full text-xs bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400">Menunggu Pelunasan</span>
    }
    if (consultation.status === "completed") {
      return <span className="px-2 py-1 rounded-full text-xs bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400">Selesai</span>
    }
    if (consultation.status === "cancelled") {
      return <span className="px-2 py-1 rounded-full text-xs bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400">Dibatalkan</span>
    }
    return <span className="px-2 py-1 rounded-full text-xs bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400">{consultation.status}</span>
  }

  const stats = [
    { label: "Orderan Baru", value: pendingOrders.length, color: "yellow" },
    { label: "Menunggu DP", value: acceptedOrders.length, color: "blue" },
    { label: "DP Lunas", value: dpPaidOrders.length, color: "green" },
    { label: "Konsultasi", value: ongoingOrders.length, color: "purple" },
    { label: "Menunggu Lunas", value: waitingPelunasanOrders.length, color: "orange" },
    { label: "Selesai", value: completedOrders.length, color: "emerald" },
  ]

  const statColors = {
    yellow: "bg-yellow-100 text-yellow-600 dark:bg-yellow-900/30 dark:text-yellow-400",
    blue: "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400",
    green: "bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400",
    purple: "bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400",
    orange: "bg-orange-100 text-orange-600 dark:bg-orange-900/30 dark:text-orange-400",
    emerald: "bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400",
  }

  const capitalizeName = (name) => {
    if (!name) return ""
    return name.split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()).join(' ')
  }

  return (
    <div>
      <div className="bg-gradient-to-r from-blue-700 to-indigo-800 rounded-2xl p-6 text-white mb-6">
        <h1 className="text-2xl font-bold">Halo, {capitalizeName(user?.nama)}</h1>
        <p className="text-blue-100 mt-1">Kelola orderan konsultasi dari client</p>
        <div className="flex flex-wrap gap-2 mt-3">
          <span className="bg-white/20 rounded-full px-3 py-1 text-sm">📋 {pendingOrders.length} Orderan Baru</span>
          <span className="bg-white/20 rounded-full px-3 py-1 text-sm">💰 {dpPaidOrders.length} DP Lunas</span>
          <span className="bg-white/20 rounded-full px-3 py-1 text-sm">💬 {ongoingOrders.length} Konsultasi</span>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 mb-6">
        {stats.map((stat, idx) => (
          <div key={idx} className={`${statColors[stat.color]} rounded-xl p-3 text-center shadow-md`}>
            <p className="text-xl font-bold">{stat.value}</p>
            <p className="text-xs">{stat.label}</p>
          </div>
        ))}
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-md overflow-hidden">
        <div className="p-5 border-b border-gray-200 dark:border-gray-700">
          <h2 className="text-lg font-bold text-gray-800 dark:text-white">📋 Daftar Konsultasi</h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 dark:bg-gray-900">
              <tr className="text-gray-700 dark:text-gray-300">
                <th className="p-3 text-left font-semibold">Client</th>
                <th className="p-3 text-left font-semibold">Kasus</th>
                <th className="p-3 text-left font-semibold">Tanggal</th>
                <th className="p-3 text-left font-semibold">Jam</th>
                <th className="p-3 text-left font-semibold">Status</th>
                <th className="p-3 text-left font-semibold">Meeting</th>
                <th className="p-3 text-left font-semibold">Aksi</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
              {myConsultations.length === 0 ? (
                <tr>
                  <td colSpan="7" className="text-center py-8 text-gray-500 dark:text-gray-400">
                    Belum ada konsultasi
                  </td>
                </tr>
              ) : (
                myConsultations.map(c => (
                  <tr key={c.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition">
                    <td className="p-3 text-gray-800 dark:text-gray-200 font-medium">{c.client_name || "-"}</td>
                    <td className="p-3 text-gray-800 dark:text-gray-200 font-semibold">{c.judul_kasus}</td>
                    <td className="p-3 text-gray-600 dark:text-gray-300">{c.tanggal_konsultasi?.split('T')[0]}</td>
                    <td className="p-3 text-gray-600 dark:text-gray-300">{c.jam_konsultasi}</td>
                    <td className="p-3">{getStatusBadge(c)}</td>
                    <td className="p-3">
                      {c.meeting_link ? (
                        <a href={c.meeting_link} target="_blank" rel="noreferrer" className="text-blue-600 dark:text-blue-400 text-sm hover:underline inline-flex items-center gap-1">
                          Join <Icons.ExternalLink />
                        </a>
                      ) : (
                        <span className="text-gray-400 dark:text-gray-500 text-sm">-</span>
                      )}
                    </td>
                    <td className="p-3">
                      <div className="flex flex-wrap gap-2">
                        {c.status === "pending" && (
                          <>
                            <button 
                              onClick={() => showConfirm(c.id, 'accept', 'Terima Orderan', `Apakah Anda yakin ingin menerima orderan "${c.judul_kasus}"?`)} 
                              disabled={loadingAction} 
                              className="bg-green-600 hover:bg-green-700 text-white px-3 py-1 rounded-lg text-xs transition"
                            >
                              Terima
                            </button>
                            <button 
                              onClick={() => showConfirm(c.id, 'reject', 'Tolak Orderan', `Apakah Anda yakin ingin menolak orderan "${c.judul_kasus}"?`)} 
                              disabled={loadingAction} 
                              className="bg-red-600 hover:bg-red-700 text-white px-3 py-1 rounded-lg text-xs transition"
                            >
                              Tolak
                            </button>
                          </>
                        )}
                        
                        {c.status === "accepted" && c.dp_payment_status === "paid" && !c.meeting_link && (
                          <button 
                            onClick={() => setShowMeetingModal(c)} 
                            className="bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded-lg text-xs transition"
                          >
                            Tambah Meeting
                          </button>
                        )}
                        
                        {c.status === "ongoing" && (
                          <button 
                            onClick={() => showConfirm(c.id, 'complete', 'Selesaikan Kasus', `Apakah Anda yakin kasus "${c.judul_kasus}" sudah selesai?`)} 
                            disabled={loadingAction} 
                            className="bg-orange-600 hover:bg-orange-700 text-white px-3 py-1 rounded-lg text-xs transition"
                          >
                            Selesaikan
                          </button>
                        )}
                        
                        {(c.status === "completed" || c.status === "cancelled" || c.status === "waiting_pelunasan") && (
                          <button 
                            onClick={() => showConfirm(c.id, 'hide', 'Hapus Riwayat', `Apakah Anda yakin ingin menghapus riwayat konsultasi "${c.judul_kasus}" dari tampilan Anda?`)} 
                            disabled={loadingAction} 
                            className="bg-red-600 hover:bg-red-700 text-white px-3 py-1 rounded-lg text-xs transition"
                          >
                            Hapus
                          </button>
                        )}
                        
                        {c.status === "waiting_pelunasan" && (
                          <span className="text-yellow-600 dark:text-yellow-400 text-xs">⏳ Menunggu Pelunasan</span>
                        )}
                        
                        {c.status === "completed" && (
                          <span className="text-green-600 dark:text-green-400 text-xs flex items-center gap-1">
                            <Icons.CheckCircle /> Selesai
                          </span>
                        )}
                        
                        {c.status === "cancelled" && (
                          <span className="text-red-600 dark:text-red-400 text-xs">✗ Dibatalkan</span>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal Tambah Meeting Link */}
      {showMeetingModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 w-full max-w-md">
            <h3 className="text-lg font-bold text-gray-800 dark:text-white mb-4">Tambah Meeting Link</h3>
            <p className="mb-1 font-medium text-gray-800 dark:text-white">{showMeetingModal.judul_kasus}</p>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">Client: {showMeetingModal.client_name}</p>
            <input 
              type="text" 
              value={meetingLink} 
              onChange={(e) => setMeetingLink(e.target.value)} 
              placeholder="https://meet.google.com/xxx" 
              className="w-full px-4 py-3 rounded-xl border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent mb-4" 
              autoFocus 
            />
            <div className="flex gap-3">
              <button 
                onClick={() => handleAddMeetingLink(showMeetingModal.id)} 
                disabled={loadingAction}
                className="flex-1 bg-blue-600 hover:bg-blue-700 text-white py-2 rounded-xl transition"
              >
                {loadingAction ? <Icons.Loading /> : "Simpan"}
              </button>
              <button 
                onClick={() => setShowMeetingModal(null)} 
                className="flex-1 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-white py-2 rounded-xl transition hover:bg-gray-300 dark:hover:bg-gray-600"
              >
                Batal
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Modal Konfirmasi */}
      <AnimatePresence>
        {confirmData.isOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-black/50"
              onClick={() => setConfirmData({ isOpen: false, id: null, action: null, title: "", message: "" })}
            />
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="relative bg-white dark:bg-gray-800 rounded-2xl shadow-2xl max-w-md w-full p-6"
            >
              <div className="text-center">
                <Icons.AlertTriangle />
                <h3 className="text-xl font-bold text-gray-800 dark:text-white mt-4">{confirmData.title}</h3>
                <p className="text-gray-500 dark:text-gray-400 mt-2 text-sm">{confirmData.message}</p>
              </div>
              <div className="flex gap-3 mt-6">
                <button
                  onClick={handleConfirm}
                  disabled={loadingAction}
                  className="flex-1 bg-red-600 hover:bg-red-700 text-white py-2.5 rounded-xl font-medium transition"
                >
                  {loadingAction ? "Memproses..." : "Ya, Lanjutkan"}
                </button>
                <button
                  onClick={() => setConfirmData({ isOpen: false, id: null, action: null, title: "", message: "" })}
                  className="flex-1 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-white py-2.5 rounded-xl font-medium hover:bg-gray-300 dark:hover:bg-gray-600 transition"
                >
                  Batal
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  )
}

export default LawyerDashboard
