// frontend/counsela/src/pages/Register.vue
<template>
  <div class="max-w-4xl mx-auto py-2 sm:py-8 text-zinc-950">
    <!-- {Header} -->
    <div class="hidden sm:flex items-center justify-between border-b border-zinc-200 pb-3 mb-8 text-[11px] font-mono text-zinc-400 uppercase tracking-wider">
      <div class="flex items-center gap-3">
        <span class="font-bold text-zinc-950">COUNSELA</span>
        <span>•</span>
        <span>PENDAFTARAN AKUN</span>
      </div>
      <div class="text-[10px] text-zinc-400 font-mono">AKUN BARU</div>
    </div>

    <div class="grid lg:grid-cols-12 gap-5 lg:gap-8 items-start">
      <!-- {Info Column} -->
      <div class="lg:col-span-5 space-y-4 sm:space-y-6 text-xs">
        <div class="space-y-1.5 sm:space-y-2">
          <h1 class="text-2xl sm:text-3xl font-bold tracking-tight text-zinc-950">
            Daftar Akun Baru
          </h1>
          <p class="text-zinc-500 leading-relaxed text-xs sm:text-sm">
            Daftarkan diri Anda untuk menjadwalkan konsultasi hukum online.
          </p>
        </div>

        <div class="hidden lg:block border-t border-zinc-100 pt-5 space-y-4">
          <div class="p-4 rounded-2xl bg-white border border-zinc-200 space-y-1.5 shadow-2xs">
            <span class="font-mono text-[10px] text-zinc-400 uppercase block font-semibold">
              Skema Pembayaran 50 / 50
            </span>
            <p class="text-zinc-500 leading-relaxed text-[11px]">
              Tarif jasa konsultasi tertera transparan. DP 50% untuk reservasi jadwal, dan pelunasan 50% setelah konsultasi selesai.
            </p>
          </div>

          <div class="p-4 rounded-2xl bg-zinc-50 border border-zinc-200 space-y-1">
            <span class="font-mono text-[10px] text-zinc-400 uppercase block font-semibold">
              Data Sesuai Identitas
            </span>
            <p class="text-[11px] text-zinc-500 leading-relaxed">
              Pastikan nama yang Anda cantumkan sesuai dengan identitas resmi (KTP/Paspor) guna keperluan administrasi konsultasi.
            </p>
          </div>
        </div>
      </div>

      <!-- {Form Column} -->
      <div class="lg:col-span-7 bg-white border border-zinc-200 rounded-3xl p-5 sm:p-8 shadow-sm">
        <div class="hidden sm:flex justify-between items-center pb-4 mb-6 border-b border-zinc-100 text-xs">
          <span class="font-bold text-zinc-950 text-sm">Formulir Pendaftaran</span>
          <span class="text-[10px] text-zinc-400 font-mono">ROLE: CLIENT</span>
        </div>

        <form @submit.prevent="handleSubmit" class="space-y-4 text-xs">
          <div>
            <label class="block text-xs font-semibold text-zinc-700 mb-1.5">
              Nama Lengkap
            </label>
            <input
              v-model="formData.nama"
              type="text"
              placeholder="Contoh: Budi Santoso"
              class="w-full px-4 py-3 rounded-2xl border border-zinc-200 bg-white text-zinc-900 focus:outline-none focus:border-black transition-colors shadow-2xs"
              required
            />
          </div>

          <div>
            <label class="block text-xs font-semibold text-zinc-700 mb-1.5">
              Alamat Email
            </label>
            <input
              v-model="formData.email"
              type="email"
              placeholder="nama@domain.com"
              class="w-full px-4 py-3 rounded-2xl border border-zinc-200 bg-white text-zinc-900 focus:outline-none focus:border-black transition-colors shadow-2xs"
              required
            />
          </div>

          <div class="grid sm:grid-cols-2 gap-3.5">
            <div>
              <label class="block text-xs font-semibold text-zinc-700 mb-1.5">
                Kata Sandi
              </label>
              <input
                v-model="formData.password"
                type="password"
                placeholder="Min. 8 karakter"
                class="w-full px-4 py-3 rounded-2xl border border-zinc-200 bg-white text-zinc-900 focus:outline-none focus:border-black transition-colors shadow-2xs"
                required
              />
            </div>

            <div>
              <label class="block text-xs font-semibold text-zinc-700 mb-1.5">
                Konfirmasi Sandi
              </label>
              <input
                v-model="formData.confirmPassword"
                type="password"
                placeholder="Ulangi sandi"
                class="w-full px-4 py-3 rounded-2xl border border-zinc-200 bg-white text-zinc-900 focus:outline-none focus:border-black transition-colors shadow-2xs"
                required
              />
            </div>
          </div>

          <div class="pt-2">
            <button
              type="submit"
              :disabled="loading"
              class="inline-flex items-center justify-center gap-2 w-full py-3.5 bg-black hover:bg-zinc-800 text-white font-semibold rounded-full text-xs sm:text-sm tracking-wide transition-all disabled:opacity-50 shadow-sm cursor-pointer"
            >
              <span>{{ loading ? 'Mendaftarkan...' : 'Daftar Akun Baru' }}</span>
              <ArrowRight v-if="!loading" class="w-4 h-4" />
            </button>
          </div>
        </form>

        <div class="mt-6 pt-5 border-t border-zinc-100 flex justify-between items-center text-xs text-zinc-500">
          <span>Sudah memiliki akun?</span>
          <RouterLink
            to="/login"
            class="inline-flex items-center gap-1 font-semibold text-zinc-950 hover:underline"
          >
            <span>Masuk ke Akun</span>
            <ArrowRight class="w-3 h-3" />
          </RouterLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight } from '@lucide/vue'
import authService from '../service/authService'
import { toast } from '../composables/useToast'

const router = useRouter()

const formData = ref({
  nama: '',
  email: '',
  password: '',
  confirmPassword: '',
})
const loading = ref(false)

const handleSubmit = async () => {
  if (formData.value.password.length < 8) {
    toast.error('Kata sandi minimal 8 karakter')
    return
  }
  if (formData.value.password !== formData.value.confirmPassword) {
    toast.error('Konfirmasi kata sandi tidak cocok')
    return
  }

  loading.value = true
  try {
    await authService.register({
      nama: formData.value.nama,
      email: formData.value.email,
      password: formData.value.password,
    })
    toast.success('Pendaftaran akun berhasil. Silakan masuk ke portal.')
    router.push('/login')
  } catch (err) {
    toast.error(err.response?.data?.message || 'Registrasi gagal, mohon periksa kembali data Anda')
  } finally {
    loading.value = false
  }
}
</script>

// frontend/counsela/src/pages/Register.jsx
import { useState } from "react"
import { Link, useNavigate } from "react-router-dom"
import { motion } from "framer-motion"
import authService from "../service/authService"
import { toast } from "react-hot-toast"

// Icons
const Icons = {
  ArrowLeft: () => (
    <svg className="w-4 h-4 group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 18l-6-6 6-6" />
    </svg>
  ),
  Eye: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
    </svg>
  ),
  EyeOff: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
    </svg>
  ),
  User: () => (
    <svg className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
    </svg>
  ),
  Mail: () => (
    <svg className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
    </svg>
  ),
  Lock: () => (
    <svg className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
    </svg>
  ),
  Loading: () => (
    <svg className="animate-spin h-5 w-5 text-white" viewBox="0 0 24 24" fill="none">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
    </svg>
  ),
  Check: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
    </svg>
  ),
}

const Register = () => {
  const navigate = useNavigate()
  const [formData, setFormData] = useState({ nama: "", email: "", password: "", confirmPassword: "" })
  const [loading, setLoading] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)

  const handleChange = (e) => setFormData({ ...formData, [e.target.name]: e.target.value })

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!formData.nama || !formData.email || !formData.password) return toast.error("Semua field wajib diisi")
    if (formData.password.length < 6) return toast.error("Password minimal 6 karakter")
    if (formData.password !== formData.confirmPassword) return toast.error("Konfirmasi password tidak cocok")
    try {
      setLoading(true)
      await authService.register({ nama: formData.nama, email: formData.email, password: formData.password })
      toast.success("Registrasi berhasil! Silakan login.")
      setTimeout(() => navigate("/login"), 1500)
    } catch (err) { toast.error(err.response?.data?.message || "Registrasi gagal") }
    finally { setLoading(false) }
  }

  return (
    <div className="min-h-screen flex flex-col lg:flex-row">
      {/* Left Side - Branding */}
      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-emerald-700 via-teal-800 to-cyan-900 relative overflow-hidden">
        <div className="absolute top-20 left-10 w-64 h-64 bg-white/10 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-20 right-10 w-80 h-80 bg-white/10 rounded-full blur-3xl animate-pulse delay-1000" />
        <div className="absolute inset-0 bg-black/20" />
        
        <div className="relative z-10 flex flex-col justify-center items-center text-white p-12 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-md"
          >
            <div className="w-24 h-24 mx-auto bg-white/20 backdrop-blur-sm rounded-3xl flex items-center justify-center mb-8 shadow-xl">
              <span className="text-5xl font-bold text-white">⚖️</span>
            </div>
            <h2 className="text-4xl font-bold mb-3">Counsela</h2>
            <p className="text-lg text-teal-100 mb-10">Bergabung dan mulai konsultasi</p>
            
            <div className="space-y-4 text-left bg-white/10 backdrop-blur-sm rounded-2xl p-6 border border-white/20">
              {[
                "Gratis mendaftar",
                "Akses ke 100+ lawyer profesional",
                "Konsultasi kapan saja"
              ].map((item, idx) => (
                <div key={idx} className="flex items-center gap-3">
                  <div className="w-6 h-6 rounded-full bg-white/20 flex items-center justify-center">
                    <Icons.Check />
                  </div>
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </div>

      {/* Right Side - Form */}
      <div className="w-full lg:w-1/2 flex items-center justify-center p-6 md:p-8 bg-white dark:bg-gray-900 min-h-screen">
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5 }}
          className="w-full max-w-md"
        >
          <Link to="/" className="inline-flex items-center gap-2 text-gray-500 hover:text-emerald-600 mb-8 transition group">
            <Icons.ArrowLeft /> Kembali ke Beranda
          </Link>
          
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-gray-800 dark:text-white">Daftar Akun</h1>
            <p className="text-gray-500 dark:text-gray-400 mt-2">Bergabung dengan Counsela sekarang</p>
          </div>
          
          <form onSubmit={handleSubmit} className="space-y-5">
            <div>
              <label className="block text-gray-700 dark:text-gray-300 text-sm font-medium mb-2">Nama Lengkap</label>
              <div className="relative">
                <Icons.User />
                <input
                  type="text"
                  name="nama"
                  value={formData.nama}
                  onChange={handleChange}
                  placeholder="Masukkan nama lengkap"
                  className="w-full px-4 py-3 pl-12 rounded-xl border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition"
                />
              </div>
            </div>
            
            <div>
              <label className="block text-gray-700 dark:text-gray-300 text-sm font-medium mb-2">Alamat Email</label>
              <div className="relative">
                <Icons.Mail />
                <input
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="contoh@email.com"
                  className="w-full px-4 py-3 pl-12 rounded-xl border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition"
                />
              </div>
            </div>
            
            <div>
              <label className="block text-gray-700 dark:text-gray-300 text-sm font-medium mb-2">Password</label>
              <div className="relative">
                <Icons.Lock />
                <input
                  type={showPassword ? "text" : "password"}
                  name="password"
                  value={formData.password}
                  onChange={handleChange}
                  placeholder="Minimal 6 karakter"
                  className="w-full px-4 py-3 pl-12 pr-12 rounded-xl border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition"
                >
                  {showPassword ? <Icons.EyeOff /> : <Icons.Eye />}
                </button>
              </div>
            </div>
            
            <div>
              <label className="block text-gray-700 dark:text-gray-300 text-sm font-medium mb-2">Konfirmasi Password</label>
              <div className="relative">
                <Icons.Lock />
                <input
                  type={showConfirmPassword ? "text" : "password"}
                  name="confirmPassword"
                  value={formData.confirmPassword}
                  onChange={handleChange}
                  placeholder="Ulangi password"
                  className="w-full px-4 py-3 pl-12 pr-12 rounded-xl border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition"
                />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition"
                >
                  {showConfirmPassword ? <Icons.EyeOff /> : <Icons.Eye />}
                </button>
              </div>
            </div>
            
            <button
              type="submit"
              disabled={loading}
              className="w-full py-3 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white font-semibold transition-all duration-200 flex items-center justify-center gap-2 shadow-md hover:shadow-lg disabled:opacity-50"
            >
              {loading ? <Icons.Loading /> : "Daftar Sekarang"}
            </button>
          </form>
          
          <div className="mt-6 text-center">
            <p className="text-gray-500 dark:text-gray-400">
              Sudah punya akun?{' '}
              <Link to="/login" className="text-emerald-600 font-semibold hover:underline">
                Login di sini
              </Link>
            </p>
          </div>
          
          <div className="mt-4 text-center">
            <p className="text-xs text-gray-400 dark:text-gray-500">
              Dengan mendaftar, Anda menyetujui Ketentuan Layanan dan Kebijakan Privasi kami
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  )
}

export default Register
