// frontend/counsela/src/components/LawyerCard.jsx
import { Link } from "react-router-dom"
import { motion } from "framer-motion"
import { useState, useEffect } from "react"
import api from "../utils/axios"
import useAuth from "../hooks/useAuth"

const Icons = {
  Star: () => (
    <svg className="w-3.5 h-3.5 inline" fill="currentColor" viewBox="0 0 20 20">
      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.538 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.783.57-1.838-.197-1.538-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
    </svg>
  ),
  Calendar: () => (
    <svg className="w-3.5 h-3.5 inline mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
  ),
  Money: () => (
    <svg className="w-3.5 h-3.5 inline mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Clock: () => (
    <svg className="w-3.5 h-3.5 inline mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  ArrowRight: () => (
    <svg className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
    </svg>
  ),
  Verified: () => (
    <svg className="w-4 h-4 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
    </svg>
  ),
  Login: () => (
    <svg className="w-3.5 h-3.5 inline mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
    </svg>
  ),
}

const LawyerCard = ({ lawyer }) => {
  const { isAuthenticated } = useAuth()
  const [scheduleText, setScheduleText] = useState("")
  const [loadingSchedule, setLoadingSchedule] = useState(true)

  useEffect(() => {
    // Hanya fetch schedule jika user sudah login
    if (!isAuthenticated || !lawyer?.id) {
      setLoadingSchedule(false)
      return
    }
    
    const fetchSchedule = async () => {
      try {
        const response = await api.get(`/lawyers/${lawyer.id}/schedule`)
        if (response.data.success) {
          const text = response.data.data.schedule_text
          setScheduleText(text.length > 60 ? text.substring(0, 60) + "..." : text)
        }
      } catch (error) {
        console.error("Gagal load jadwal:", error)
      } finally {
        setLoadingSchedule(false)
      }
    }
    fetchSchedule()
  }, [lawyer?.id, isAuthenticated])

  if (!lawyer) return null

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      whileHover={{ y: -8 }}
      transition={{ duration: 0.4 }}
      viewport={{ once: true }}
      className="group relative bg-white dark:bg-gray-800 rounded-2xl overflow-hidden shadow-lg hover:shadow-2xl transition-all duration-300"
    >
      {/* Badge Rating */}
      <div className="absolute top-3 right-3 z-10 bg-yellow-400 dark:bg-yellow-500 px-2.5 py-1 rounded-full text-xs font-bold shadow-lg flex items-center gap-1">
        <Icons.Star />
        <span>{lawyer.rating || "0"}</span>
      </div>

      {/* Verified Badge */}
      {lawyer.status_aktif && (
        <div className="absolute top-3 left-3 z-10 bg-green-500 px-2 py-1 rounded-full text-xs font-bold shadow-lg flex items-center gap-1">
          <Icons.Verified />
          <span className="text-white">Aktif</span>
        </div>
      )}

      {/* Foto */}
      <div className="relative h-48 md:h-56 overflow-hidden bg-gradient-to-br from-gray-300 to-gray-400 dark:from-gray-700 dark:to-gray-800">
        <img
          src={lawyer.foto_profil || "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500"}
          alt={lawyer.firma_hukum || "Lawyer"}
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
          onError={(e) => {
            e.target.src = "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500"
          }}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />
      </div>

      {/* Konten */}
      <div className="p-5">
        <h3 className="text-lg font-bold text-gray-800 dark:text-white truncate">
          {lawyer.firma_hukum || "Firma Hukum"}
        </h3>
        <p className="text-blue-600 dark:text-blue-400 mt-1 font-medium text-sm">
          {lawyer.spesialisasi || "Spesialisasi"}
        </p>
        
        <div className="mt-3 flex items-center justify-between text-sm">
          <span className="text-gray-500 dark:text-gray-400 flex items-center">
            <Icons.Calendar /> {lawyer.pengalaman || 0} tahun
          </span>
          <span className="text-gray-500 dark:text-gray-400 flex items-center">
            <Icons.Money /> Rp {Number(lawyer.tarif_konsultasi || 0).toLocaleString("id-ID")}
          </span>
        </div>

        {/* Jam Kerja - Hanya tampil jika user sudah login */}
        {isAuthenticated ? (
          <div className="mt-3 p-3 bg-gray-50 dark:bg-gray-700/50 rounded-xl">
            <p className="text-xs text-gray-500 dark:text-gray-400 flex items-start gap-1">
              <Icons.Clock />
              <span className="flex-1">{loadingSchedule ? "Memuat..." : (scheduleText || "Jam kerja belum diatur")}</span>
            </p>
          </div>
        ) : (
          <div className="mt-3 p-3 bg-gray-50 dark:bg-gray-700/50 rounded-xl text-center">
            <Link to="/login" className="text-xs text-blue-600 dark:text-blue-400 flex items-center justify-center gap-1 hover:underline">
              <Icons.Login /> Login untuk lihat jadwal
            </Link>
          </div>
        )}

        {/* Tombol Lihat Detail */}
        <Link
          to={`/lawyers/${lawyer.id}`}
          className="mt-4 flex items-center justify-center gap-1 w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white py-2.5 rounded-xl transition-all duration-300 shadow-md group-hover:shadow-lg text-sm font-medium"
        >
          Lihat Detail
          <Icons.ArrowRight />
        </Link>
      </div>
    </motion.div>
  )
}

export default LawyerCard

// frontend/counsela/src/components/LawyerCard.vue
<template>
  <div
    v-if="lawyer"
    class="bg-white border border-zinc-200/90 rounded-2xl sm:rounded-3xl p-3 sm:p-5 flex flex-col justify-between shadow-2xs hover:shadow-md hover:border-black hover:-translate-y-0.5 transition-all duration-200 text-zinc-950 group relative"
  >
    <div class="absolute top-2.5 right-2.5 sm:top-3.5 sm:right-3.5 z-10 flex items-center gap-1 bg-white/95 sm:bg-zinc-100/90 px-1.5 sm:px-2 py-0.5 sm:py-1 rounded-full border border-zinc-200/80 shadow-2xs">
      <input
        :id="`compare-${lawyer.id}`"
        type="checkbox"
        :checked="isCompared"
        @change="$emit('toggle-compare', lawyer)"
        class="w-3.5 h-3.5 rounded text-black focus:ring-0 cursor-pointer accent-black"
        aria-label="Pilih untuk komparasi"
      />
      <label :for="`compare-${lawyer.id}`" class="text-[10px] sm:text-[11px] font-medium text-zinc-600 cursor-pointer select-none hidden sm:inline">
        Bandingkan
      </label>
    </div>

    <div class="space-y-2.5 sm:space-y-4 pt-0.5">
      <div class="flex flex-col sm:flex-row items-start gap-2 sm:gap-3.5 sm:pr-20">
        <div class="relative shrink-0">
          <img
            :src="lawyer.foto_profil || defaultAvatar"
            :alt="lawyer.firma_hukum || 'Advokat'"
            @error="handleImgError"
            class="w-11 h-11 sm:w-13 sm:h-13 rounded-xl sm:rounded-2xl object-cover border border-zinc-200 bg-zinc-100 shadow-2xs group-hover:scale-105 transition-transform duration-200"
            loading="lazy"
          />
          <span
            v-if="lawyer.status_aktif"
            class="absolute -bottom-0.5 -right-0.5 w-2.5 h-2.5 sm:w-3 sm:h-3 rounded-full bg-emerald-500 border-2 border-white"
            title="Aktif Menerima Klien"
          ></span>
        </div>

        <div class="flex-1 min-w-0 w-full">
          <h3 class="font-bold text-xs sm:text-sm text-zinc-950 leading-snug line-clamp-1 group-hover:text-zinc-700 transition-colors">
            {{ lawyer.firma_hukum || 'Firma Hukum' }}
          </h3>

          <p v-if="lawyer.nama && lawyer.nama !== lawyer.firma_hukum" class="text-[11px] text-zinc-700 font-medium truncate hidden sm:block">
            {{ lawyer.nama }}
          </p>

          <p class="text-[10px] sm:text-xs text-zinc-500 truncate mt-0.5 font-medium">
            {{ lawyer.spesialisasi }}
          </p>

          <div class="flex flex-wrap items-center gap-1 sm:gap-1.5 mt-1 sm:mt-1.5">
            <span class="inline-flex items-center gap-1 text-[10px] sm:text-[11px] font-semibold px-1.5 sm:px-2 py-0.5 rounded-full bg-zinc-100 text-zinc-900 border border-zinc-200">
              <Star class="w-2.5 h-2.5 sm:w-3 sm:h-3 text-zinc-900 fill-zinc-900" />
              <span>{{ Number(lawyer.rating || 5).toFixed(1) }}</span>
            </span>

            <span class="text-[10px] sm:text-[11px] font-medium px-1.5 sm:px-2 py-0.5 rounded-full bg-zinc-100 text-zinc-600 border border-zinc-200">
              {{ lawyer.pengalaman || 0 }} Thn
            </span>
          </div>
        </div>
      </div>

      <div class="hidden sm:flex items-center justify-between text-[11px] border-y border-zinc-100 py-2 text-zinc-600 font-medium">
        <span class="flex items-center gap-1.5 text-zinc-800">
          <ShieldCheck class="w-3.5 h-3.5 text-zinc-900" />
          <span>Advokat Berizin Resmi</span>
        </span>
        <span class="text-zinc-400 text-[10px] font-mono">SESI PRIVAT</span>
      </div>

      <div class="py-1.5 px-2.5 sm:py-2.5 sm:px-3.5 bg-zinc-50 border border-zinc-200/80 rounded-xl flex justify-between items-center text-xs">
        <div>
          <span class="text-zinc-400 text-[9px] sm:text-[11px] font-medium block">Tarif Sesi</span>
          <span class="text-[9px] sm:text-[11px] text-zinc-500 hidden sm:block">Sesi 60 Menit</span>
        </div>
        <div class="text-right">
          <span class="font-bold text-zinc-950 text-xs sm:text-sm block">
            Rp {{ formattedFee }}
          </span>
          <span class="text-[9px] sm:text-[10px] font-mono text-zinc-500 hidden sm:block">
            DP 50%: Rp {{ formattedDp }}
          </span>
        </div>
      </div>
    </div>

    <div class="pt-2 sm:pt-1">
      <RouterLink
        :to="`/lawyers/${lawyer.id}`"
        class="sm:hidden block w-full text-center py-2 px-2 text-[11px] font-semibold bg-black text-white hover:bg-zinc-800 rounded-xl transition-all shadow-2xs"
      >
        Lihat Profil
      </RouterLink>

      <div class="hidden sm:grid sm:grid-cols-2 gap-2">
        <RouterLink
          :to="`/lawyers/${lawyer.id}`"
          class="text-center py-2 px-3 text-xs font-semibold border border-zinc-200 hover:border-black hover:bg-zinc-50 text-zinc-900 rounded-xl transition-all"
        >
          Lihat Profil
        </RouterLink>

        <RouterLink
          :to="`/consultation/new?lawyer=${lawyer.id}`"
          class="inline-flex items-center justify-center gap-1.5 text-center py-2 px-3 text-xs font-semibold bg-black hover:bg-zinc-800 text-white rounded-xl transition-all shadow-sm"
        >
          <span>Jadwalkan</span>
          <ArrowRight class="w-3.5 h-3.5" />
        </RouterLink>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { ArrowRight, ShieldCheck, Star } from '@lucide/vue'

const props = defineProps({
  lawyer: {
    type: Object,
    required: true,
  },
  isCompared: {
    type: Boolean,
    default: false,
  },
})

defineEmits(['toggle-compare'])

const defaultAvatar =
  'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=400&q=80'

const handleImgError = (e) => {
  e.target.src = defaultAvatar
}

const feeNumber = computed(() => Number(props.lawyer?.tarif_konsultasi || 0))

const formattedFee = computed(() => {
  return feeNumber.value.toLocaleString('id-ID')
})

const formattedDp = computed(() => {
  return Math.floor(feeNumber.value / 2).toLocaleString('id-ID')
})
</script>
